### ISSUE TITLE
@Cleanup does not function for variables declared in for-each loops.

### ISSUE THREAD

**Issue by m-kuklinski** [rzwitserloot/lombok#1839] opened 2018-08-28 00:01 UTC
One cannot annotate a variable declared and assigned to within the header of a for-each loop with `@Cleanup`, as the library does not recognize the variable as being initialized.

I would expect the following to work:

`for (@Cleanup var someObj : container) ...`

**Comment by janrieke** [comment] 2018-08-28 08:36
It's hard to imagine what you'd expect as the intended behavior for this. The most likely is that lombok should add the cleanup code at the end of the `for` loop (because it is the end of the variable's scope). However, this will alter the contents of the `container`, breaking any use of its contents after the loop. This is dangerous.
Besides, although `@Cleanup` is attached to the variable, its _meaning_ is primarily connected the instance, because the instances has to be cleaned. The variable just carries the annotation.

So the only reasonable extension to ease your case I see is to allow cleaning up collections. Then you could add the annotation on the definition of `container`, and lombok could loop through the collection at the end of its scope. However, I don't know if that is implementable, and I doubt that there is a larger need for it.

**Comment by m-kuklinski** [comment] 2018-08-28 17:17
In this situation, we have a really weird setup where `close` is overloaded to finalize an object, and trigger an update of the parent container (without changing its structure - it just replaces a container element), and the containers are lists. So, closing the object basically finishes the pending operations, but doesn't alter the container.

I actually wouldn't expect a `close` to ever alter the container that the object is contained by - it should alter the object, but I would imagine the container would generally maintain the same reference to the now-closed object, as Java doesn't have any concept of things like RAII.

**Comment by janrieke** [comment] 2018-08-28 17:49
I was not phrasing it very good when I wrote "will alter the contents of the `container`"; of course the collection elements will stay the same, but their state will be changed.
However, I now recognize that you could already achieve such a problematic setup right now:

	InputStream in = new FileInputStream("");
	if (true) {
		@Cleanup InputStream in2 = in;
	}
	in.read();

Allowing `@Cleanup` in for-each loop variable definitions would not introduce a new kind of problem. So I withdraw my objection in this regard.

**Comment by rspilker** [comment] 2018-09-17 19:59
I also have a problem with this coding style, although I can understand that it sometimes makes sense.

In general, we are talking about an ownership problem. Who is responsible for closing a resource. Typically, it is the code that created it.

In the Enhanded For-loop, the ownership of 'things to close' should typically not transfer to the loop.

I think the best we can do now is generate an error if you use @Cleanup on a loop variable.

**Comment by rspilker** [comment] 2018-09-17 20:15
The current behavior is enhanced for-loop is: `ERROR: @Cleanup variable declarations need to be initialized.`
For the old-style for-loop it is: `ERROR @Cleanup is legal only on a local variable declaration inside a block.`

I do agree that the error message for enhanced for-loop could be better, but at least your code won't compile, so there is no problem of accidentally leaving resources open.

**Closed by rspilker** 2018-09-17 20:15 UTC

**Comment by ameisen** [comment] 2018-10-14 18:39
(I am @m-kuklinski on my personal account)

As per @janrieke, though, are we this doesn't really introduce a new problem, nor protect us from one.

You can mimic the same behavior, as said, by just doing:

`
for (val _stream : streams) {
	@Cleanup val stream = _stream;
	...
}
`

Arguably, that's _worse_ than it originally was, whereas the syntax:

`
for (@Cleanup val stream : streams) {
	...
}
`

... is clearer as to its intent, as it doesn't have two references to the object floating around in scope.

I'm just not sure why the library is prohibiting users from doing it - whether it's bad practice or not is subjective, but it seems odd to me to prevent a user from doing something that the library author(s) consider bad practice - it is usually best to defer to the user, and not require the user to use odd syntax to do it. That _could_ just be the C++-programmer in me, though.
