### ISSUE TITLE
[BUG] @ExtensionMethod fails in Eclipse 2019-03

### ISSUE THREAD

**Issue by gadton** [rzwitserloot/lombok#2236] opened 2019-09-13 10:08 UTC
Eclipse 2019-03 fails to compile code using `ExtensionMethod` whereas Maven does.

Eclipse is reporting
`The method or(T, Supplier<T>) in the type MyExtensionsTest.MyExtensions is not applicable for the arguments (String)`

Here's a simplified test to reproduce:
```
@ExtensionMethod(MyExtensions.class)
public class MyExtensionsTest {
    @Test
    public void test() {
        String v = "value";
        assertThat( v.or( () -> "default" ), equalTo( "value" ) );

        String n = null;
        assertThat( n.or( () -> "default" ), equalTo( "default" ) );
    }

    public static class MyExtensions {
        public static <T> T or( T object, Supplier<T> ifNullProducer ) {
            return object != null ? object : ifNullProducer.get();
        }
    }
}
```
lombok 1.18.10
eclipse 2019-03
java 11 (zulu11.31.11 winx64)
maven 3.6.1, same JDK

**Comment by rzwitserloot** [comment] 2020-02-27 21:44
Duplicate of #1441

**Closed by rzwitserloot** 2020-02-27 21:44 UTC
