### ISSUE TITLE
[BUG] @Builder on class level: Cannot make a static reference to the non-static 

### ISSUE THREAD

**Issue by nimo23** [rzwitserloot/lombok#2354] opened 2020-02-04 13:13 UTC
**Describe the bug**
I get the message 

`Cannot make a static reference to the non-static method hashCode() from the type Object`

when using 

```
@Getter
@Setter
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class User {

// the hashCode comes from Object.hashCode
@Builder.Default
private String tmpId = Integer.toHexString(hashCode());
}
```

I dont know if this is a bug, because no compiler error is shown if I put the `@Builder` at constructor-level instead:

```
...
@Builder
public User(String tmpId){
this.tmpId = Integer.toHexString(hashCode());
}
...
```

**Version info (please complete the following information):**
 - Lombok version: actual version
 - Platform java 12

**Comment by rzwitserloot** [comment] 2020-02-04 14:11
This is intentional behaviour; lombok is working as intended.

In java, you CAN do what you're trying to pull here, but it causes all sorts of wonky behaviour and is explicitly called out in many style guides as 'things not to do'. When java creates objects, there are 2 separate 'tracks' of code that need to be run _for each layer in the hierarchy_ (so for your class, and your parent's class, and your parent's parent, all the way to j.l.Object). If you put in one of these tracks any code that has instance scope, you've got yourself a tricky chicken-and-egg problem where final fields hold values you never assigned to them, to name one 'Whaaaa????' thing that happens then.

And you're doing that here.

Perhaps your explicit impl of hashCode does not use any instance state, but that's bizarre; for example, lombok's own hashCode would look at your own tmpId as part of the hashCode to generate. Not only would 'tmpId' be null, which is probably fine, but any other field, even one with a default or an explicit value associated to it with the builder is also blank. The hashcode so generated is likely a constant value for all objects created regardless of what values you set and _CLEARLY_ not what you wanted.

Java regretfully allows this crazy broken stuff that you shouldn't be doing, but that doesn't mean lombok is going to. That expression is static context.

You're going to have to find another way.

**Closed by rzwitserloot** 2020-02-04 14:11 UTC
