### ISSUE TITLE
Getter return null with Lombok Builder and Jackson together

### ISSUE THREAD

**Issue by zhengye1** [rzwitserloot/lombok#2037] opened 2019-02-04 17:41 UTC
I using Lombok version 1.18.0 in my spring boot project, and here is the request body I use in post man
```
{
	"RetailTransactionGenericRequest":{
		"dateTime": "2019-02-04T16:50:40.740Z",
		"origin":{
			"retailerName":"retailerName",
			"accessID":"accessID",
			"currencyCode": "CAD",
			"storeID":"storeID",
			"termID": "terminalID"
		},
		"product":{
			"amount": 20,
			"code":"code",
			"upc":"UPC"
		},
		"transactionID": "201902041650403164912"
	}
}
```

So in my entity class I create following:
```
package entity;
// imports

@Data
@Builder(builderClassName = "RetailTransactionGenericRequestWrapperBuilder", toBuilder = true)
@JsonDeserialize(builder = RetailTransactionGenericRequestWrapper.RetailTransactionGenericRequestWrapperBuilder.class)
public class RetailTransactionGenericRequestWrapper {
    @JsonProperty
    private RetailTransactionGenericRequest RetailTransactionGenericRequest;

    @JsonPOJOBuilder(withPrefix = "")
    public static class RetailTransactionGenericRequestWrapperBuilder{

    }

    @Override
    public String toString(){
        return ReflectionToStringBuilder.toString(this, ToStringStyle.JSON_STYLE);
    }
}
```

```
package com.itsp.incommcall.entity;

//imports

@Data
@Getter
@Builder(builderClassName = "RetailTransactionGenericRequestBuilder", toBuilder = true)
@JsonDeserialize(builder = RetailTransactionGenericRequest.RetailTransactionGenericRequestBuilder.class)
public class RetailTransactionGenericRequest {

    @JsonProperty
    private String dateTime;
    @JsonProperty
    private Origin origin;
    @JsonProperty
    private Product product;
    @JsonProperty
    private String transactionID;

    @JsonPOJOBuilder(withPrefix = "")
    public static class RetailTransactionGenericRequestBuilder{

    }

    @Override
    public String toString(){
        return ReflectionToStringBuilder.toString(this, ToStringStyle.JSON_STYLE);
    }

}
```

```
package entity;
//imports

@Data
@Getter
@Builder(builderClassName = "OriginBuilder", toBuilder = true)
@JsonDeserialize(builder = Origin.OriginBuilder.class)
public class Origin {

    @JsonProperty
    @Builder.Default
    private String accessID = "defaultid";

    @JsonProperty

    private String currencyCode;

    @JsonProperty
    @Builder.Default
    private String retailerName = "default retail name";

    @JsonProperty
    private String storeID;

    @JsonProperty
    private String termID;

    @JsonProperty
    private String posEntryMode;

    @JsonPOJOBuilder(withPrefix = "")
    public static class OriginBuilder {

    }

    @Override
    public String toString() {
        return ReflectionToStringBuilder.toString(this, ToStringStyle.JSON_STYLE);
    }
}
```
```
package entity;
//imports

@Data
@Getter
@Builder(builderClassName = "ProductBuilder", toBuilder = true)
@JsonDeserialize(builder = Product.ProductBuilder.class)
public class Product {

    @JsonProperty
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private double amount;

    @JsonProperty
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String code;

    @JsonProperty
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String upc;

    // Response part
    @JsonProperty
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private MetaFields metafields;

    @JsonProperty
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String balance;

    @JsonProperty
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String status;


    @JsonPOJOBuilder(withPrefix = "")
    public static class ProductBuilder{

    }

    @Override
    public String toString(){
        return ReflectionToStringBuilder.toString(this, ToStringStyle.JSON_STYLE);
    }
}
```

In my controller class, I use the parameter `@RequestBody RetailTransactionGenericRequestWrapper wrapper` in my controller method, and when I try to access the `RetailTransactinGenericRequest` object by invoke `wrapper.getRetailTransactinGenericRequest`, I got `null`,  and break down my rest of the code, what did I did wrong?

**Comment by janrieke** [comment] 2019-02-04 20:47
This is most likely not an issue in Lombok. Such a question is better placed at Stackoverflow.
That being said, you could place method breakpoints even on Lombok generated methods to find out what goes wrong on the call (or if they are called at all).

**Comment by rzwitserloot** [comment] 2019-02-19 00:50
Yeah, sounds like it's not a lombok issue. But if it is, sounds like it's a duplicate of @2042

**Closed by rzwitserloot** 2019-02-19 00:50 UTC
