### ISSUE TITLE
Bug:@SuperBuilder can't support @NonNull

### ISSUE THREAD

**Issue by liudaomanbu** [rzwitserloot/lombok#1895] opened 2018-10-12 03:15 UTC
```
@SuperBuilder
public abstract class Parent {
  @NonNull
  Number number;
}
```
```
@SuperBuilder
public class Child extends Parent {

  @Singular
  ImmutableList<Long> ids;
}
```
![image](https://user-images.githubusercontent.com/21155988/46845925-18763a00-ce10-11e8-8f5c-35e1df7d6e79.png)
compile error

**Comment by janrieke** [comment] 2018-10-12 05:18
Duplicate of #1800 and already fixed in the current edge release.

**Closed** 2018-10-15 18:40 UTC
