### ISSUE TITLE
Scaling issues on high DPI displays

### ISSUE THREAD

**Issue by peterstritzinger** [rzwitserloot/lombok#1889] opened 2018-10-09 13:10 UTC
My Lenovo Yoga Pro has a high resolution of 3200x1800 with scaling at 300% => the Lombok UI useless.
The problem is that i can either resize nore maximize the window. See following screenshot.

![delme_lombok](https://user-images.githubusercontent.com/26869780/46671440-12484980-cbd5-11e8-939e-1dda52fbd0d0.PNG)

My Story: As a lombok UI user I would like to be able to maximize or resize the window.

**Comment by rspilker** [comment] 2018-10-15 18:45
Duplicate, solved by recent java versions.
[Why we closed this issue](https://github.com/rzwitserloot/lombok/wiki/ISSUES:-Why-we-close-issues-without-a-lot-of-explanation.)

**Closed by rspilker** 2018-10-15 18:45 UTC

**Comment by peterstritzinger** [comment] 2018-10-16 08:11
Hi,
sorry to say that but "solved by recent java versions" is in my eyes not a satisfying anwser.
Could you please provide more information.
By "duplicate" you probably mean https://github.com/rzwitserloot/lombok/issues/1355
I can not find a solution there either.

Thx

**Comment by anandchakru** [comment] 2019-03-06 13:08
Making it a fixed size window is the root cause.
Created a [PR#2057](https://github.com/rzwitserloot/lombok/pull/2057) for a fix
