### ISSUE TITLE
[FEATURE] Add @Inherited to lombock annotations

### ISSUE THREAD

**Issue by vivienlegrand** [rzwitserloot/lombok#2144] opened 2019-05-31 09:45 UTC
**Describe the feature**
You can have multiple lombock annotation in classes. And a lot of time, you always put the sames annotations in each classes depending on the context or the project. The goal of this feature is to allow users to redefine an annotation that merge multiple lombock annotations.  
For instance, if you want to have POJO objects with a builder, today you need to add on all POJOs :
```java
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
class MyPojo {}
```
If we have the inheritance on lombock annotation, we would have the ability to create a new one : 
```java
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.TYPE)
public @interface PojoWithBuilder {
}
```
With this, you will only need to add to all your classes the following annotation : 
```java
@PojoWithBuilder
class MyPojo {} 
```

**Describe the target audience**
All programmers that use heavily lombock will benefic from this feature. That gonna give them the ability to have code more clean and more readable.

**Additional context**
I don't now how lombock work under the hood and if this feature is easy or not to implement. From what I've understand in the [@Inherited doc](https://docs.oracle.com/javase/8/docs/api/java/lang/annotation/Inherited.html), the lombock annotation should be automatically query if a custom annotation is present in the class.

**Comment by Maaartinus** [comment] 2019-06-01 05:51
@vivienlegrand 
> I don't now how lombock work under the hood

Count yourself lucky. :rofl: 

This request is a duplicate of many others, e.g.,  #557.

To summarize:
- Annotating annotations is fine per se, but the project owners consider this case to be  a terrible misuse.
- Alternative syntax has been proposed (not only one), but that's not the problem.
- We all agree, that such a feature would be very useful.
- AFAIK nobody implemented anything yet.
- Hacking on Lombok is much more complicated than annotation processing or even reflection.
- AFAIK annotation inheritance would not help at all, as accessing any information outside of the file being processed is [close to impossible](https://github.com/rzwitserloot/lombok/wiki/LOMBOK-CONCEPT:-Resolution).

**Comment by rspilker** [comment] 2019-06-03 12:23
Duplicate of #557

**Closed by rspilker** 2019-06-03 12:23 UTC
