### ISSUE TITLE
generator field constant string in java

### ISSUE THREAD

**Issue by qifuren1985** [rzwitserloot/lombok#1268] opened 2016-12-22 08:26 UTC
For example, in ORM we often define a class Like this:
```
class DealDB {
    pubic String dealId;
}
```
with eclipse or IDEA, we can generate get and set method, but we cannot generate field name constant string. When we write query code in java, we often need this constant string.
```
class DealDB {
    public String dealId;

    // to generate this
    public static final String FIELD_DEALID="dealId";
}
```

**Comment by edpichler** [comment] 2017-02-17 09:19
Could you explain it better?

**Comment by evser** [comment] 2017-11-07 18:27
Very desirable feature!

**Comment by nikowitt** [comment] 2017-11-07 19:01
Sounds like a duplicate of https://github.com/rzwitserloot/lombok/issues/1152.

**Comment by victorwss** [comment] 2018-04-25 18:42
IMO, this should be closed. This is indeed a duplicate of #1152 relating to the PR #46.

**Closed** 2021-02-02 16:31 UTC
