### ISSUE TITLE
Spring Maven -Werror [ERROR] An unknown compilation problem occurred

### ISSUE THREAD

**Issue by jrybak2312** [rzwitserloot/lombok#2285] opened 2019-11-07 12:24 UTC
Compilation fails with -Werror and Lombok in Spring Boot project with the message "An unknown compilation problem occurred"

```
<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <compilerArgs>
                        <arg>-Xlint:all</arg>
                        <arg>-Werror</arg>
                    </compilerArgs>
                </configuration>
</plugin>
```

Steps to reproduce:
1. Open the sample project [spring-lombok-werror-bug-demo.zip](https://github.com/rzwitserloot/lombok/files/3819512/spring-lombok-werror-bug-demo.zip)
2. run `mvn clean package` in the root of the project (Apache Maven 3.6.1, Java 1.8.0_231 or 11.0.4, maven-compiler-plugin 3.8.1)

It's maybe related to https://github.com/rzwitserloot/lombok/issues/1339

**Comment by jrybak2312** [comment] 2019-11-07 13:07
Same issue in the maven-compiler-plugin JIRA:
https://issues.apache.org/jira/browse/MCOMPILER-403

**Comment by devdotlog** [comment] 2019-11-08 05:26
it'not lombok issue. The same error occurs if you remove the lombok dependency from pom.xml and run mvn clean package. 

Apply the lint option as follows:

```
    <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
            <compilerArgs>
                <arg>-Werror</arg>
            </compilerArgs>
            <args>
                <arg>-Xlint:all</arg>
            </args>
        </configuration>
    </plugin>
```

**Comment by jrybak2312** [comment] 2019-11-08 09:48
@devdotlog thanks for your reply. But I tried to remove Lombok and replace the current config with the xml above. And the issue is not reproducible in this case 😕

**Comment by jakub-bochenski** [comment] 2019-11-15 12:50
I think this is a duplicate of https://github.com/spring-projects/spring-boot/issues/6421#issuecomment-233591004
To make it pass use `-Xlint:-processing`

**Comment by jrybak2312** [comment] 2020-01-15 12:33
@jakub-bochenski thanks it works as expected if add `<showWarnings>true</showWarnings>` 
https://issues.apache.org/jira/browse/MCOMPILER-403?focusedCommentId=16975072&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16975072

**Closed** 2020-01-20 13:49 UTC
