### ISSUE TITLE
[BUG] @Builder(toBuilder=true) on static method throws NullPointerException

### ISSUE THREAD

**Issue by merusso** [rzwitserloot/lombok#2721] opened 2021-01-21 19:12 UTC
**Describe the bug**

Using `@Builder(toBuilder = true)` on a static factory method produces a NullPointerException.

This code worked previously on v1.18.12 and broke on v1.18.14.

Trimmed exception stack trace:
(full stack trace is 166 lines from mostly Gradle code, but I can provide if desired)
```
java.lang.NullPointerException
        at lombok.javac.handlers.HandleBuilder.handle(HandleBuilder.java:374)
        at lombok.javac.HandlerLibrary$AnnotationHandlerContainer.handle(HandlerLibrary.java:113)
        at lombok.javac.HandlerLibrary.handleAnnotation(HandlerLibrary.java:256)
        at lombok.javac.JavacTransformer$AnnotationVisitor.visitAnnotationOnMethod(JavacTransformer.java:89)
        at lombok.javac.JavacNode.traverse(JavacNode.java:138)
        at lombok.javac.JavacAST.traverseChildren(JavacAST.java:138)
        at lombok.javac.JavacNode.traverse(JavacNode.java:105)
        at lombok.javac.JavacAST.traverseChildren(JavacAST.java:138)
        at lombok.javac.JavacNode.traverse(JavacNode.java:95)
        at lombok.javac.JavacAST.traverseChildren(JavacAST.java:138)
        at lombok.javac.JavacNode.traverse(JavacNode.java:95)
        at lombok.javac.JavacAST.traverseChildren(JavacAST.java:138)
        at lombok.javac.JavacNode.traverse(JavacNode.java:90)
        at lombok.javac.JavacAST.traverse(JavacAST.java:134)
        at lombok.javac.JavacTransformer.transform(JavacTransformer.java:63)
        at lombok.javac.apt.LombokProcessor.process(LombokProcessor.java:326)
        at lombok.core.AnnotationProcessor$JavacDescriptor.process(AnnotationProcessor.java:187)
        at lombok.core.AnnotationProcessor.process(AnnotationProcessor.java:237)
        at lombok.launch.AnnotationProcessorHider$AnnotationProcessor.process(AnnotationProcessor.java:90)
        at org.gradle.api.internal.tasks.compile.processing.DelegatingProcessor.process(DelegatingProcessor.java:62)
        at org.gradle.api.internal.tasks.compile.processing.IsolatingProcessor.process(IsolatingProcessor.java:50)
        at org.gradle.api.internal.tasks.compile.processing.DelegatingProcessor.process(DelegatingProcessor.java:62)
        at org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor.access$401(TimeTrackingProcessor.java:37)
        at org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor$5.create(TimeTrackingProcessor.java:99)
        at org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor$5.create(TimeTrackingProcessor.java:96)
        at org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor.track(TimeTrackingProcessor.java:117)
        at org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor.process(TimeTrackingProcessor.java:96)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:980)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:896)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1222)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1334)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1258)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:936)
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:104)
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:147)
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:94)
        at org.gradle.api.internal.tasks.compile.AnnotationProcessingCompileTask.call(AnnotationProcessingCompileTask.java:93)
        at org.gradle.api.internal.tasks.compile.ResourceCleaningCompilationTask.call(ResourceCleaningCompilationTask.java:57)
        at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:54)
        at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:39)
        [...]
```

**To Reproduce**

Source reproducing issue:
```java
package lombok;

public class LombokTest {

    public static void main(String[] args) {
        One one = One.builder().name("one").build();
        System.out.println("one = " + one);
    }
    
    // This use is broken
    @AllArgsConstructor(access = AccessLevel.PRIVATE)
    public static class One {
        private String name;
        
        @Builder(toBuilder = true)
        private static One create(String name) {
            // arbitrary init logic
            return new One(name);
        }
    }
    
    // This use works
    @Builder(toBuilder = true)
    public static class Two {
        private String name;
        
        private static Two create(String name) {
            // arbitrary init logic
            return new Two(name);
        }
    }

    // This use works
    @AllArgsConstructor(access = AccessLevel.PRIVATE)
    public static class Three {
        private String name;
        
        @Builder
        private static Three create(String name) {
            // arbitrary init logic
            return new Three(name);
        }
    }
}
```

**Expected behavior**
Code should compile successfully, producing builder methods as desired.

```java
public static class One {
    private String name;

    private One(String name) {
        this.name = name;
    }

    private static One create(String name) {
        // arbitrary init logic
        return new One(name);
    }

    public static OneBuilder builder() {
        return new OneBuilder();
    }

    public OneBuilder toBuilder() {
        return new OneBuilder().name(this.name);
    }

    public static class OneBuilder {
        private String name;

        OneBuilder() {
        }

        public One.OneBuilder name(String name) {
            this.name = name;
            return this;
        }

        public One build() {
            return One.create(name);
        }

        public String toString() {
            return "LombokTest.One.OneBuilder(name=" + this.name + ")";
        }
    }
}
```

**Version info (please complete the following information):**
- Lombok version: 1.18.16 (works on 1.18.12, broken on 1.18.14)
- Platform:
  - java: 11.0.6
    ```
    $ java -version
    openjdk version "11.0.6" 2020-01-14
    OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
    OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)
    ```
  - gradle: v6.4.1
    ```
    ------------------------------------------------------------
    Gradle 6.4.1
    ------------------------------------------------------------
    
    Build time:   2020-05-15 19:43:40 UTC
    Revision:     1a04183c502614b5c80e33d603074e0b4a2777c5
    
    Kotlin:       1.3.71
    Groovy:       2.5.10
    Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
    JVM:          11.0.6 (AdoptOpenJDK 11.0.6+10)
    OS:           Mac OS X 10.15.7 x86_64
    ```
**Additional context**

As shown in the code example, this problem does not occur when not setting `toBuilder=true` (default is false), or when using this annotation on the class instead of a static method.

**Comment by Rawi01** [comment] 2021-01-27 16:37
This is a duplicate of #2657 and fixed in the current edge version

**Closed** 2021-01-27 16:39 UTC
