### ISSUE TITLE
Support Gradle's upcoming incremental annotation processing feature

### ISSUE THREAD

**Issue by eximius313** [rzwitserloot/lombok#1662] opened 2018-04-17 13:30 UTC
Gradle 4.7 with support for [Incremental annotation processing](https://docs.gradle.org/4.7-rc-2/release-notes.html#incremental-annotation-processing) is going to be released tomorrow.
Can Lombok support it?

**Comment by Maaartinus** [comment] 2018-04-17 13:33
Let's hope, it will. Duplicate of #1580.

**Closed** 2018-04-17 13:41 UTC
