### ISSUE TITLE
any annontation equals @EnumId in lombok-pg

### ISSUE THREAD

**Issue by AndyChenW** [rzwitserloot/lombok#1130] opened 2016-06-14 09:58 UTC
Really need another annotation for getting one of the Enum by it's field.

 found @EnumId here:

http://peichhorn.github.io/lombok-pg/EnumId.html

Any lombok annotation equals to it? If not, any plan to support it?

**Comment by rspilker** [comment] 2017-05-15 21:04
Duplicate of #706

**Closed by rspilker** 2017-05-15 21:04 UTC
Labels: duplicate
