### ISSUE TITLE
[BUG] generate wrong setter/getter method

### ISSUE THREAD

**Issue by CarlosWuu** [rzwitserloot/lombok#2688] opened 2020-12-31 05:42 UTC
**Describe the bug**
when I declare a property like 'xXxx',lombok will generate setter/getter method like 
setXXxx()/getXXxx()

**To Reproduce**

**Expected behavior**
setxXxx()/getxXxx()

**Version info (please complete the following information):**
 - Lombok version 1.16.12
 - Platform jdk 1.8.0_201-b09

**Additional context**

**Comment by rzwitserloot** [comment] 2021-01-02 14:27
Duplicate of #2693

**Closed by rzwitserloot** 2021-01-02 14:27 UTC
