### ISSUE TITLE
[BUG] https://issues.apache.org/jira/browse/NETBEANS-1842

### ISSUE THREAD

**Issue by FoxXav** [rzwitserloot/lombok#2656] opened 2020-11-24 16:15 UTC
**Describe the bug**
Hi,

I wanted to report this issue open for Netbeans but no solutions has been proposed from this side so I'll try in the lombok side.
To complete what is in the JIRA ticket, the issu is not limited to Windows but also Linux

When using lombok, generated methods show as errors in editor.  "reference to <methodname> is ambiguous   both method <methodname> in <classname> and method <methodname> in <classname> match".

**To Reproduce**
A project using lombok with netbeans with nb-javac installed and running

**Expected behavior**
No error in netbeans editor

**Version info (please complete the following information):**
 - Lombok version (1.16.x I havent tested with lesser as I used feature not available in below version)
 - Netbeans (not tested before 9)
 - JDK 8 (OpenJDK)

**Comment by Rawi01** [comment] 2020-11-24 16:33
Hi, I recently fixed a lombok bug in Netbeans and as far as I know the latest lombok edge version works properly in Netbeans 12. Can you share an example file/project?

**Comment by FoxXav** [comment] 2020-11-24 16:49
I have tested today with the edge version but still the same issue, I'll try to do a sample project

**Comment by FoxXav** [comment] 2020-11-25 16:30
I try making a sample project but did not succeeded to reproduce.
But doing so by looking at our original project,  seems to be related to netbeans nb-javac plugin and/or the background indexation process.
As I finally found the file generated by netbeans (/home/user/.cache/netbeans/12.1/index/xxxxxx/myClasses.sig) corresponding to one of my error showned in the editor (the .sig file is in fact a .class used behind the seen by netbeans.
And if I decompile this class (with jd-gui) I note that there really are 2 methods (for each fields) with the same signature but not the same implementation.

Exemple of what is present in this class :
```
  public FilterTypeEnum getTypeFiltrage() {
    throw new RuntimeException("Uncompilable source code");
  }
  public FilterTypeEnum getTypeFiltrage() {
    return this.typeFiltrage;
  }
```

**Comment by Rawi01** [comment] 2020-11-25 17:46
Thanks for your investigations, does this also happens in a smaller project? I'm still unable to reproduce the issue.

**Comment by FoxXav** [comment] 2020-11-25 17:56
That's the problem I have perhaps with the sample project I started to do. I took some of the classes that causes issue in my "big" project but no luck to reproduce in the sample.
So the numbers of classes involved may be in cause but it's to confirm, I continue when I can to investigate those point.

**Comment by dyorgio** [comment] 2020-11-29 18:33
Hello guys, I have problems with lombok and "Autosave" feature of NetBeans after 1.18.10.... sometimes I try to upgrade it when I see a updated version and the problem is the same.
So, the point of rupture was introduced after 1.18.10 (it works well).
@FoxXav I also use java 14 and build with java 8, but 1.18.10 is ok, after alter your version, close NetBeans and delete all index cache folder.

**Comment by Rawi01** [comment] 2020-11-29 21:33
@dyorgio The same or a different problem? There is a known issue in 1.18.16 that is already fixed in the edge version. If it is the same problem (ambiguous methods) it would be great if you can provide a sample project and steps to reproduce the issue. If it is something else please create a new detailed issue.

**Comment by dyorgio** [comment] 2020-11-29 21:39
@Rawi01 The same, in NetBeans notifications tell abouut nbjavac errors and if you build maven projects (without clean phase) javac inform about duplicated signatures on projects affected.
I enter here today to open a new issue, this is an old issue, since 1.18.10 I can't upgrade lombok version... but than I found this one ... I will try edge version and inform here if it was fixed.

**Comment by dyorgio** [comment] 2020-11-29 21:47
Confirmed, now it is working (no errors on compilation).
I removed/included fields and getters and setters appears on NetBeans navigator normally.
I tried to change access too, no problems... 👍

**Comment by FoxXav** [comment] 2020-12-01 17:00
Hi when I try with the edge version the issue remained. I will retry to be sure.

**Comment by FoxXav** [comment] 2020-12-09 14:47
Hi, 
Just installed netbeans 12.2 in the hope it would work but no luck.
But doing so I got a new error message which I think could help a lot. In our project we have another annotation processor used hibernate-jpamodel and this one seems to be the real culprit behind the scene. This annotation processor use Jaxb which was removed since Java11.
`java.lang.NullPointerException
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:914)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$2500(JavacProcessingEnvironment.java:113)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1298)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1380)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1350)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1240)
	at com.sun.tools.javac.api.JavacTaskImpl.enter(JavacTaskImpl.java:404)
	at com.sun.tools.javac.api.JavacTaskImpl.enterTrees(JavacTaskImpl.java:451)
[catch] at org.netbeans.modules.java.source.nbjavac.indexing.MultiPassCompileWorker.compile(MultiPassCompileWorker.java:204)
	at org.netbeans.modules.java.source.indexing.JavaCustomIndexer.index(JavaCustomIndexer.java:361)
	at org.netbeans.modules.parsing.spi.indexing.Indexable$MyAccessor$2.run(Indexable.java:138)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater.runIndexer(RepositoryUpdater.java:275)
	at org.netbeans.modules.parsing.spi.indexing.Indexable$MyAccessor.index(Indexable.java:136)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work.doIndex(RepositoryUpdater.java:2750)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work.access$800(RepositoryUpdater.java:2154)
...`
Annotation processing error:      java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException          org.hibernate.jpamodelgen.xml.JpaDescriptorParser      <init>      60                    org.hibernate.jpamodelgen.JPAMetaModelEntityProcessor      init      99    `
`
the annotation processor in this case is run I believe by the IDE java version (in my case Java14 and not the target Java8) which could explain the wrong classes issued by annotation processor.

I don't know how I can add jaxb to netbeans module so nbjavac got jaxb but I think the problem is here.

**Comment by FoxXav** [comment] 2020-12-17 13:24
The issue is now really in the netbeans side.

Thanks

**Closed** 2020-12-17 13:23 UTC
