### ISSUE TITLE
[BUG] When the first letter of an attribute is lowercase and the second letter is uppercase, the getter and setter methods generated by Lombok are incorrect

### ISSUE THREAD

**Issue by lw5946** [rzwitserloot/lombok#2149] opened 2019-06-05 08:19 UTC
In the JavaBean specification, getter and setter methods of `pDept` attributes are `getpDetp` and `setpDept`. But the getter and setter methods generated by Lombok are `getPDetp` and `setPDept`.

I used version 1.16.14, but I didn't see a new version fixing the bug in changelog.

**Comment by maxxyme** [comment] 2019-06-05 11:49
Hi @lw5946 

I'd really like you provide some evidence of your saying. Because I just (discovered and) read the JavaBeans Specification 1.01 available on Oracle's website: https://www.oracle.com/technetwork/articles/javaee/spec-136004.html

Particularly this chapter 8.8 but there's nothing related to this exception (except what I have put in **bold** but it's about all-uppercase properties).

> 8.8 Capitalization of inferred names.
> 
> When we use design patterns to infer a property or event name, we need to decide what rules
to follow for capitalizing the inferred name. If we extract the name from the middle of a normal
mixedCase style Java name then the name will, by default, begin with a capital letter.
> 
> Java programmers are accustomed to having normal identifiers start with lower case letters.
Vigorous reviewer input has convinced us that we should follow this same conventional rule
for property and event names.
> 
> Thus when we extract a property or event name from the middle of an existing Java name, we
normally convert the first character to lower case. **However to support the occasional use of all
upper-case names, we check if the first two characters of the name are both upper case and if
so leave it alone.** So for example,
“FooBah” becomes “fooBah”
“Z” becomes “z”
“URL” becomes “URL”
We provide a method Introspector.decapitalize which implements this conversion rule.

**Comment by hj819748949** [comment] 2019-06-06 00:52
@maxxyme 
for example:
lombok entity, lombok Generate getter, setter
`@Getter
@Setter
public class LUser
{
	private String tEst;
	
	private String tDate;
	
	private String ttttttDate;
}`

eclipse Generate getter, setter
`public class EUser
{
	private String tEst;
	
	private String tDate;
	
	private String ttttttDate;
	
	
	public String gettEst()
	{
		return tEst;
	}
	public void settEst(String tEst)
	{
		this.tEst = tEst;
	}
	public String gettDate()
	{
		return tDate;
	}
	public void settDate(String tDate)
	{
		this.tDate = tDate;
	}
	public String getTtttttDate()
	{
		return ttttttDate;
	}
	public void setTtttttDate(String ttttttDate)
	{
		this.ttttttDate = ttttttDate;
	}
}
`

test
`@Test
	public void testLombok()
	{
		LUser lu = new LUser();
		lu.setTDate("xxx");                 // lombok  The first t character is capitalized
		lu.setTEst("xxxx");                 // lombok The first t character is capitalized
		lu.setTtttttDate("werevfegv");      // lombok The first t character is capitalized
	}
	@Test
	public void testEclipse()
	{
		EUser eu = new EUser();
		eu.settDate("xxx");                 // eclipse   First t character lowercase
		eu.settDate("xxxx");                // eclipse   First t character lowercase
		eu.setTtttttDate("werevfegv");      // eclipse   First t character lowercase
	}`

The getter and setter generated by the two have character case differences, and if you use jackson serialization into json, there is a problem of json's name case.

https://github.com/FasterXML/jackson-databind/issues/2327

**Comment by Maaartinus** [comment] 2019-06-06 15:50
IMHO duplicate of #927.

@lw5946 This is an old news.... the Javabeans crap is [inconsistent in itself](https://groups.google.com/d/msg/project-lombok/c9WKYhlfe8k/zYEm8g6QUEsJ) and what Lombok implements is not optimal. IIRC the team knows it and would accept a PR, but not change it themselves - as it's a lot of work with backwards incompatible changes for switching from one interpretation to a more frequently used one. Too little gain. Search for Javabeans in this repo if you want to know more.

**Comment by lw5946** [comment] 2019-06-10 02:35
Oh, well, thank you.

**Comment by lsong98sh** [comment] 2019-08-09 01:17
So, why not add an annotation attribute such as  @Getter(convention=NamingConvention.Eclipse)

**Comment by rzwitserloot** [comment] 2020-01-15 17:36
lombok's behaviour is intentional. We will not change it and we will not be putting in a convention toggle. Not worth the effort or the maintenance burden.

**Closed by rzwitserloot** 2020-01-15 17:36 UTC

**Comment by rzwitserloot** [comment] 2021-01-02 14:28
Duplicate of #2693
