### ISSUE TITLE
Compile error when static-importing a field from @UtilityClass

### ISSUE THREAD

**Issue by ghost** [rzwitserloot/lombok#1186] opened 2016-09-08 11:13 UTC
How to reproduce:
1. Define a public constant in a @UtilityClass (AnnotatedUtilityClass.java in example)
2. Static import this constant in another class (StaticImportingClass.java in example)
3. Run 'mvn compile'

Attached minimal example:
[lombok-utility-class-issue.zip](https://github.com/rzwitserloot/lombok/files/461451/lombok-utility-class-issue.zip)

**Comment by hobbypunk90** [comment] 2017-02-01 12:23
I've the same problem with a static import of the whole utility class.

**Comment by askoning** [comment] 2017-02-13 12:06
This also occurs without Lombok. It's not possible to static import within the same package.
```$ cat Main.java   
import static Utility.*;

public class Main {
        Main() {
                String s = FOO;
        }
}```

```$ cat Utility.java 
public final class Utility {
        public static final String FOO = "Foo";
}```

```$ javac *.java
Main.java:1: error: cannot find symbol
import static Utility.*;
              ^
  symbol: class Utility
Main.java:5: error: cannot find symbol
                String s = FOO;
                           ^
  symbol:   variable FOO
  location: class Main
2 errors```

Static importing a field from a @UtilityClass in another package should work just fine - at least, I can't reproduce the issue with the latest release.

**Comment by oliverboehme** [comment] 2017-03-02 10:41
> It's not possible to static import within the same package.
That is new to me.

Also I'm quite sure that I first encountered this problem when importing from a different package.

**Comment by mmlinford** [comment] 2018-07-17 21:04
I don't have a lot of time to investigate right now, but I can confirm that this is still happening in lombok 1.18.0.

class MyClass is in package a.b.c
class MyUtilityClass is in package a.b.c.d

MyClass.java does `import static a.b.c.d.MyUtilityClass.someMethod`. When I try to compile, seemingly *all* lombok annotations failed to process. When I switch to just calling `MyUtilityClass.someMethod()` without the static import, things work fine.

However, if I go to MyUtilityClass and give the method a `static` modifier by hand, it compiles fine again.

I'll try to post a gist or something when I have time. Thanks.

**Comment by rzwitserloot** [comment] 2019-02-18 22:00
Duplicate of #2044

**Closed by rzwitserloot** 2019-02-18 22:00 UTC
