### ISSUE TITLE
Java 9 Maven Compiling Issue

### ISSUE THREAD

**Issue by lalib** [rzwitserloot/lombok#1482] opened 2017-10-03 19:40 UTC
Hi there,

I am getting an error compiling the project with maven. Here are the logs;

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by lombok.javac.apt.LombokProcessor to field com.sun.tools.javac.processing.JavacProcessingEnvironment.processorClassLoader
WARNING: Please consider reporting this to the maintainers of lombok.javac.apt.LombokProcessor
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.036 s
[INFO] Finished at: 2017-10-03T21:34:58+02:00
[INFO] Final Memory: 38M/127M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project X: Fatal error compiling: java.lang.NoClassDefFoundError: com/sun/tools/javac/file/BaseFileObject: com.sun.tools.javac.file.BaseFileObject -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

```

Java version : 9
Lombok version: 1.16.18
Maven version: 3.5.0
Maven compiler plugin version: 3.1

Can you help me please?

**Comment by rspilker** [comment] 2017-10-05 20:12
The solution is to add some `-J--add-opens` arguments to the compiler, however, that won't help you for now because of a bug in the compiler-plugin. Please vote for issue [MCOMPILER-291](https://issues.apache.org/jira/browse/MCOMPILER-291) to get this fixed.

One other thing, it did compile on my machine, but possibly I just didn't fail on warnings.

**Comment by rspilker** [comment] 2017-10-05 20:37
Duplicate of #1471

**Closed by rspilker** 2017-10-05 20:37 UTC
