### ISSUE TITLE
Variables with similar names - "Cannot find Symbol" for getter method

### ISSUE THREAD

**Issue by mrieman** [rzwitserloot/lombok#2590] opened 2020-10-02 14:59 UTC
I believe I have encountered a bug where Lombok build fails when 2 variables with very similar names. In this example, the only difference is a single character capitalization. 

`import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

@EqualsAndHashCode @ToString @Setter @Builder
@NoArgsConstructor @AllArgsConstructor
public class History implements java.io.Serializable {

  //UpperCase "I" in this variable name`
  @Getter
  private Integer histDeIdPtr;

  //LowerCase "i" in this variable name`
  @Getter
  private Integer histDeidPtr;

}`

Building via Maven, this causes 
`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project lombok-pojos: Compilation failure: Compilation failure: 
[ERROR] /C:/git/lombok-pojos/src/main/java/org/test/lombok/pojos/History.java:[27,1] cannot find symbol
[ERROR]   symbol: method getHistDeIdPtr()`

NOTES on my setup:
- I cannot change the method names since the getter/setter methods are referenced by "closed" jars that are out of my control. 
- Eclipse compiles this fine with no errors
- All other POJO classes build fine
- These POJO are generated. 
- The Lombok annotations are added during the POJO generation via a template. 

One workaround is to write my own getter/setter. But doing so would complicate the POJO generation templates, or require after-processing; both of which I would like to avoid. 

If this is not a bug, is another workaround available?

**Comment by Rawi01** [comment] 2020-10-02 23:21
I can confirm that lombok only generates one getter if there are two fields sharing the same name with different upper and lower case characters. It's quite funny that `@EqualsAndHashCode` and `@ToString` still try to use these methods. Seems to be a bug.

**Comment by Lekanich** [comment] 2020-10-03 10:57
I think the root cause is here. It's because lombok checks getter names without case sensitivity.
I'm curious why...

**Comment by Rawi01** [comment] 2020-10-10 06:50
Original issue: https://github.com/rzwitserloot/lombok/issues/148, https://groups.google.com/g/javaposse/c/4AzRsqJdzKM

It seems like the reason for this behaviour is to handle cases where someone wants to add a method like `getURL` by hand and not generate a lomobk method. As that could also solved using `@Getter(AccessLevel.NONE)` I think that lombok should switch back to case sensitv method name comparision.

Disclaimer: I'm not a project owner.

**Comment by aloktech** [comment] 2020-10-12 12:16
Hi,
@Data
@Builder
public class History implements Serializable {
    private Integer histDeldPtr;
    private Integer histDeidPtr;
}
The above piece of code generates a proper class file, without any issue in JDK 8(IntelliJ).

**Comment by rzwitserloot** [comment] 2021-01-02 14:11
Duplicate of #2130: We won't fix this, for reasons, see that issue.

**Closed by rzwitserloot** 2021-01-02 14:11 UTC
