### ISSUE TITLE
[BUG] Exception occurs using annotation implicitcreation to create setter and getter method

### ISSUE THREAD

**Issue by ChanaLii** [rzwitserloot/lombok#2162] opened 2019-06-26 02:53 UTC
**Describe the bug**
Exception occurs using annotation implicitcreation to create setter and getter method

**To Reproduce**
using this block of code occured error log when compiler 
`@Setter
@Getter
public class TaSellerVo {
    /**
     * user id
     */
    private Integer id;
}`

using this block of code it's working
`@Setter
@Getter
public class TaSellerVo {
    private Integer id;
}`

**Expected behavior**
compilation successful

**Version info (please complete the following information):**
 - Lombok version 
` <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.6</version>
        </dependency>`

 - Platform
javaVersion：jdk7
compilation log：
`Error:java: Lombok annotation handler class lombok.javac.handlers.HandleSetter failed on C:\MyTools\codeCloud\xxxxxxxxxxxxxxxxxxxxxxxx.java: java.lang.NoSuchMethodError: java.util.Map.putIfAbsent(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;`

**Comment by rspilker** [comment] 2019-07-24 20:36
Sorry. We shouldn't have used `Map.putIfAbsent`, since it was only introduced in 1.8.

**Comment by rspilker** [comment] 2019-07-24 21:18
Duplicate of #2066, already fixed in 1.18.8.

**Closed by rspilker** 2019-07-24 21:18 UTC

**Comment by ChanaLii** [comment] 2019-07-25 01:38
> Sorry. We shouldn't have used `Map.putIfAbsent`, since it was only introduced in 1.8.

get it.
