### ISSUE TITLE
1.16.14 does not work in NetBeans (1.16.12 does work)

### ISSUE THREAD

**Issue by alvint** [rzwitserloot/lombok#1348] opened 2017-03-29 15:05 UTC
Some change between 1.16.12 and 1.16.14 causes Maven projects in NetBeans to not detect code generated by the `@Data` annotation properly. I'm using NetBeans 8.2 w/ JDK 1.8 on macOs.

In 1.16.12, all I need to do is add Lombok to my POM file and everything in NetBeans works as it should:

```
<dependency>
  <groupId>org.projectlombok</groupId>
  <artifactId>lombok</artifactId>
  <version>1.16.12</version>
  <scope>provided</scope>
  <optional>true</optional>
</dependency>
```

If I add a `@Data` annotation to a class, the generated methods are detected in NetBeans and I can use the methods in code completion. However, if I change the version of Lombok to 1.16.14, no generated methods are detected by NetBeans, CC for the generated methods is not available, and attempts to use a generated method results in NetBeans displaying an error. The project *does* compile properly, however:

<img width="519" alt="screen shot 2017-03-29 at 11 25 14 am" src="https://cloud.githubusercontent.com/assets/622202/24462641/7bc27f6e-1472-11e7-81dc-e9ee9a553f85.png">

<img width="522" alt="screen shot 2017-03-29 at 11 26 40 am" src="https://cloud.githubusercontent.com/assets/622202/24462693/a60e87a4-1472-11e7-824f-ee2bc912b625.png">

Using `@Getter` and `@Setter` on individual fields does appear to work.

**Comment by rspilker** [comment] 2017-03-29 15:35
Can you try version 1.16.16, it has jdk9 support, which is probably the cause of your problems

**Comment by alvint** [comment] 2017-03-29 16:35
Yep, 1.16.16 works! An issue is that the most recent version of Spring Boot (1.5.2) dependency management includes version 1.16.14, so people using it who don't explicitly override the version in their POM may have problems. Not sure what the solution for that is.

**Comment by alvint** [comment] 2017-03-29 16:38
So 1.16.16 removes JDK9 support?

**Comment by mtbadi39** [comment] 2017-03-29 18:36
duplicate of #1194

**Comment by rspilker** [comment] 2017-03-30 00:19
@alvint no, 1.16.16 adds jdk9 support.

**Closed by rspilker** 2017-03-30 00:19 UTC
