### ISSUE TITLE
Static import of builder class breaks bytecode generation in Maven

### ISSUE THREAD

**Issue by jelmo** [rzwitserloot/lombok#979] opened 2015-11-26 12:31 UTC
I have a class Foo annotated with @Builder. 

```
@Builder
public class Foo {
    ...
}
```

I use the generated class Foo.FooBuilder in Bar, but I statically import Foo.Builder so that I can refer directly to FooBuilder in the code:

```
import static my.org.Foo.FooBuilder
public class Bar {
  public void bar() {
    FooBuilder builder = Foo.builder();
    ...
  }
}
```

In IntelliJ with the Lombok plugin, this compiles and works fine.
However, when building with Maven, this breaks completely the whole bytecode generation phase. All Lombok generated classes and methods, even from other unrelated Lombok annotations, are rejected by javac with 'cannot find symbol' errors. 
If I remove the static import and change the code to `Foo.FooBuilder builder = Foo.builder()` everything works as expected...

Using Lombok 1.16.6 with Java 8.

**Comment by collinpeters** [comment] 2015-12-15 00:54
:+1:

**Comment by barsifedron** [comment] 2016-01-07 09:55
+1

**Comment by nvdh** [comment] 2016-01-14 07:53
+1
also, the Eclipse plugin hasn't any problems with it either

**Comment by zaretskyy** [comment] 2016-02-04 15:06
+1

**Comment by btiernay** [comment] 2016-03-10 15:33
As happens with static import of custom `buildMethodName` builder methods

**Comment by cartagena** [comment] 2016-04-25 17:05
+1

Happens with static import.

**Comment by radcortez** [comment] 2016-08-08 15:53
+1

**Comment by rporrass** [comment] 2016-08-23 09:06
+1

**Comment by BaronNoir** [comment] 2017-01-30 13:15
+1

**Comment by awasiljew** [comment] 2017-02-13 01:07
+1
Using lombok v 1.16.6, JDK 1.8.0_112

**Comment by Carthan** [comment] 2017-02-16 11:53
+1

**Comment by omega09** [comment] 2017-03-01 00:04
Using Gradle, define the following classes:

```
package p1;

import static p2.StaticContainer.getSomeInt;

public class Tester {}
```

and

```
package p2;

import lombok.Getter;

public class StaticContainer {

	@Getter private static int someInt;

//	public static int getSomeInt() { return someInt; }
}
```

Run the `build` command. You will get the following error:

> Execution failed for task ':compileJava'.
> \> Compilation failed; see the compiler error output for details.

> error: cannot find symbol
> import static p2.StaticContainer.getSomeInt;
> ^
>   symbol:   static getSomeInt
>   location: class

Note that replacing the import declaration with the wildcard:

    import static p2.StaticContainer.*;

fixes the problem, as well as explicitly writing the method.

**Comment by malumatos** [comment] 2017-07-06 12:37
+1

**Comment by m31collision** [comment] 2017-07-17 16:01
Faced out with such error today using lombok 1.16.18, JDK 1.8.0_60

**Comment by yasammez** [comment] 2017-09-19 07:32
+1

**Comment by vananiev** [comment] 2017-09-21 17:14
+1

**Comment by Meokme** [comment] 2017-11-13 10:34
+1

**Comment by FatCash** [comment] 2018-05-16 13:09
+1, same issue with Gradle 4.7, lombok 1.16.20

**Comment by kamilbeben** [comment] 2018-07-16 09:46
Experienced similar issue, while using static imports for static getter generated by lombok.
IntelliJ sees no problem there, but when rebuilding 
Versions:
lombok: 1.16.18, 
javac: 1.8.0_151, 
maven: 3.3.9

**Comment by lars-sh** [comment] 2018-09-14 21:39
I ran into the same problem and figured out the following. Does that either help some one else or even helps solving these problems?

1. My first class is annotated with `@UtilityClass`. The contained method actually does not need the modifier `static`, as it's added by Delombok at a later time.
2. My second class imports that method in a static way.

```
@UtilityClass
class FirstClass {
	public void exampleMethod() {}
}
```

```
import static FirstClass.exampleMethod;

class SecondClass {}
```

When using Delombok via Maven I got the above described `error: cannot find symbol`, but after adding the `static` modifier to `FirstClass.exampleMethod` the error went away.

That's why I guess, there's some inconsistency between the compiler loading static imports and the new structures being generated by lombok.

**Comment by lars-sh** [comment] 2018-10-12 01:08
I read that some time ago, sorry then.

One suggestion: Since adding the static keyword solves the chicken and egg problem why not adding a config flag to disallow non-static methods for @UtilityClasses?

In case you'd tell me where the static keyword is added inside Lombok and an example on reading the config values I'd even like to help with this.

**Comment by rzwitserloot** [comment] 2019-02-18 22:14
@lars-sh That'd mean `@UtilityClass` does pretty much nothing.

**Comment by rzwitserloot** [comment] 2019-02-18 22:14
Duplicate of #2044

**Closed by rzwitserloot** 2019-02-18 22:14 UTC

**Comment by Maaartinus** [comment] 2019-02-18 23:57
@rzwitserloot 
> > Since adding the static keyword solves the chicken and egg problem why not adding a config flag to disallow non-static methods for @UtilityClasses?

> That'd mean `@UtilityClass` does pretty much nothing.

Not exactly. A possibility to annotate a class as a utility class and get this checked at compile time together with an annotation to search for is useful in itself.

Actually, I was wanting such a feature when I found myself having a utility class mixing methods with and without the `static` declaration.
