### ISSUE TITLE
Eclipse property refactoring should update getter / setter references

### ISSUE THREAD

**Issue by lombokissues** [rzwitserloot/lombok#210] opened 2015-07-14 19:43 UTC
_Migrated from Google Code (issue 137)_

**Comment by ractive** [comment] 2015-10-28 11:16
Any news on this issue? I think it's a very common thing to rename a field which is now only possible with workarounds... :disappointed:

**Comment by rgra** [comment] 2015-11-12 19:06
I have a fix ready and will create a pull request after some clean-up. This will fix refactoring problems with @Data and @Getter/@Setter.

@rzwitserloot: did you try to add test cases in lombok for eclipse refactoring? would be good to test if it's broken again in later eclipse releases.

**Comment by nicoschl** [comment] 2016-11-27 22:51
Any news on when the pull request will be considered?

**Comment by rzwitserloot** [comment] 2017-01-19 23:41
Addressed in the next release due to a patch by @rgra.

**Closed by rzwitserloot** 2017-01-19 23:41 UTC

**Comment by fbastien** [comment] 2023-10-31 15:51
@rzwitserloot Why was this issue closed? If I understand correctly, the patch #1060 by @rgra prevents Eclipse from trying to modify the source code at the position of the Lombok annotation, which is actually really appreciated to avoid corrupting the annotated class, but it still doesn't address the original issue explained by steve.skrla. I'm currently using Lombok in version 1.18.4 and the issue is still present : references to getter, setter and builder methods generated by Lombok are not refactored, so Eclipse rightfully raises a compilation error on all other pieces of code calling these methods since methods with old names doesn't exist anymore. This requires the dev tu manually update the method names all over the place which is really annoying.
Could this issue be reopened please?

**Comment by Rawi01** [comment] 2023-11-01 07:47
This works for some time now, I added tests in May 2022 for it. To also refactor getters and setters in eclipse you have to set the checkbox in the refactor dialog (or open that dialog if you use the quick rename)

**Comment by fbastien** [comment] 2023-11-22 13:53
@Rawi01 Yeah sorry, my mistake, I didn't know about these checkboxes, I'm indeed used to quick rename. Thanks for the tip!
