### ISSUE TITLE
[FEATURE] Property Change Listener Support Annotation

### ISSUE THREAD

**Issue by AgnibhaBose** [rzwitserloot/lombok#2128] opened 2019-05-19 13:09 UTC
An annotation to support property change listener on selected properties is a welcoming change. I want to use a property change listener and as the getter setters are injected by lombok itself so there is no way for me to fire the property change events manually. For that it is better if you can add that with the current set of annotations or somehow guide me how can I achieve this.

TIA

**Comment by rspilker** [comment] 2019-05-21 20:07
Duplicate of #100

**Closed by rspilker** 2019-05-21 20:07 UTC
