### ISSUE TITLE
Add @Property and @FXProperty annotations

### ISSUE THREAD

**Issue by claudio-rosati** [rzwitserloot/lombok#1614] opened 2018-03-16 10:01 UTC
Add a single annotation that integrate all the aspects of a java property, something similar to the following (asterisks used for default values):

```java
@Property( 
    getter="*true*/false", 
    setter="*true*/false", 
    indexed="true/*false*",
    bound="true/*false*",
    constrained="true/*false*"
)
```

That annotation should build getter, setter, property and vetoable change listeners, final static PROPERTY_<name> field, and all the boilerplate code according to the annotation attributes (somehow similar to what the NetBeans Add Property command does). A `@Properties` annotation with similar parameters could be provided to annotate a class.

Similarly for us JavaFX developer the following annotation will be as useful as the previous one:

```java
@FXProperty ( style = FXProperty.Style.BASIC )
```

Where styles are the ones described in the [JavaFX Property Cook Book](https://wiki.openjdk.java.net/display/OpenJFX/JavaFX+Property+Architecture) (with possibly more annotation attributes if required by some styles).

That would be much appreciated.

**Comment by nlisker** [comment] 2019-04-07 00:16
Looks like a duplicate of #1222.

**Comment by rspilker** [comment] 2019-05-21 19:45
Duplicate

**Closed by rspilker** 2019-05-21 19:45 UTC
