### ISSUE TITLE
[BUG] @SuperBuilder with Generics

### ISSUE THREAD

**Issue by MertOzdogan** [rzwitserloot/lombok#2278] opened 2019-10-31 20:27 UTC
Details could be found here;

https://stackoverflow.com/questions/58641279/wrong-number-of-arguments-with-lombok

**Comment by janrieke** [comment] 2019-10-31 20:41
Does this affect both Eclipse and maven/gradle builds?

**Comment by MertOzdogan** [comment] 2019-10-31 20:47
@janrieke I do work on IJ, and for maven build, yes it does effect.

**Comment by janrieke** [comment] 2019-10-31 20:52
Also when running maven manually (not from IJ)?

**Comment by janrieke** [comment] 2019-11-01 09:56
I just checked it myself: This is not an IJ plugin bug. It affects only javac, Eclipse compilation works.

**Comment by rzwitserloot** [comment] 2019-12-19 02:18
Duplicate of #2262 See PR #2273  for fix.

**Closed by rzwitserloot** 2019-12-19 02:18 UTC
Labels: duplicate
