### ISSUE TITLE
Building a Java 8 Project in a JDK 10 fails with lombok

### ISSUE THREAD

**Issue by scravy** [rzwitserloot/lombok#1665] opened 2018-04-19 07:47 UTC
I am using edge (as lombok 1.16.20 was not working at all using JDK 10) `version: 1.16.21 (2018-04-09 22:47:18 UTC)`.

```$ java -version
java version "10.0.1" 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)
$ uname -mprs
Darwin 17.5.0 x86_64 i386
```

I have a Java 8 project which I am building with maven. The build does not complete with the following IllegalArgumentException:

```java.lang.IllegalArgumentException: Problems in URI 'file://lombok/dummy/ForceNewRound0.java' (file://lombok/dummy/ForceNewRound0.java)
	at lombok.javac.apt.LombokFileObjects$Java9Compiler.toPath(LombokFileObjects.java:187)
	...
Caused by: java.lang.IllegalArgumentException: URI has an authority component
	at java.base/sun.nio.fs.UnixUriUtils.fromUri(UnixUriUtils.java:53)
```

The URI `file://lombok/dummy/ForceNewRound0.java` is in fact not an acceptable file path on a unix system. `lombok` is taken to be the authority component (i.e. a hostname). It should be `file:///lombok/dummy/ForceNewRound0.java` (note the triple slash). Then again this would refer to a directory lombok in the root directory so I guess that somehow a relative path slipped in here where there should be an absolute path.

This does not happen if I try to build a Java 9 project.

**Comment by tmurakam** [comment] 2018-04-19 13:54
I think this is duplicate of #1657

**Comment by rspilker** [comment] 2018-04-30 21:56
The latest [edge release](https://projectlombok.org/download-edge) should work.

**Closed by rspilker** 2018-04-30 21:56 UTC
