### ISSUE TITLE
[FEATURE] @Model shortcut

### ISSUE THREAD

**Issue by nimo23** [rzwitserloot/lombok#2306] opened 2019-12-09 23:21 UTC
**Describe the feature**
Actually I have entities having all the same lombok annotations

```
// lombok dependency hell 
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Entity {

..}
```

Would be nice to provide another annotation like `@Model `which is a **shortcut** for `@Getter`, `@Setter`, `@Builder`, `@NoArgsConstructor`, `@AllArgsConstructor`.

```
@Model
public class Entity {

..}
```

**Comment by rzwitserloot** [comment] 2020-01-15 12:32
Closed: Duplicate of #2294

**Closed by rzwitserloot** 2020-01-15 12:32 UTC
