### ISSUE TITLE
[BUG] getter and setter method consistent with the rules

### ISSUE THREAD

**Issue by rainlinsu** [rzwitserloot/lombok#2266] opened 2019-10-19 09:46 UTC
I am terribly sorry for my poor English.
**Describe**
The first word is a lowercase letter, the second uppercase, getter/setter method not consistent with the rules

**To Reproduce**
```
@Data
public class User {
    private String uName;
}
```
```
        User user = new User();
        // should be getuName()
        user.setUName("Jim");
```
getter/setter method should be getuName()/setuName()

**Version**
```
	<groupId>org.projectlombok</groupId>
	<artifactId>lombok</artifactId>
	<version>1.18.10</version>
	<scope>provided</scope>
```

**Comment by Maaartinus** [comment] 2019-10-20 16:12
Duplicate of #757.

**Closed** 2019-10-21 12:04 UTC

**Comment by rzwitserloot** [comment] 2021-01-02 14:28
Duplicate of #2693
