### ISSUE TITLE
Gradle compilation error with JDK8 (_65)

### ISSUE THREAD

**Issue by dfernandezm** [rzwitserloot/lombok#971] opened 2015-11-19 17:33 UTC
I checked javac -classpath lombok.jar GetterTest.java (Simple file with @Getter) works fine with Java 8.

However invoked through Gradle compileJava task (confirmed lombok is in the classpath by printing it) fails in every single annotation (does not detect any getter, setter etc)

I tried to use `provided` configuration instead of `compile` but no luck. 

This build works fine when using JDK 7.

Is this a known issue? Should I report it in Gradle itself?

**Comment by rzwitserloot** [comment] 2015-11-22 22:33
Can you upload a zip or some such someplace with a bare bones gradle project that is failing for you? I can't reproduce this. Perhaps you have AP processing turned off? Which gradle version are you using?

provided/compile shouldn't matter.

**Comment by dfernandezm** [comment] 2015-11-25 10:40
Hi, thanks for your response.

Before attaching anything, this was all working with Java 7, so I though did not need to turn on AP or anything. How do I do that? Is there something else I need to be aware of specific to Java 8? 

I am currently using Gradle 2.2.1.

I guessed that provided/compile should not matter... Any bits of guidance would be appreciated.

It is going to be difficult to strip down the project, but I'll try to extract the bits that are failing if I cannot figure it out with your next response.

**Comment by dfernandezm** [comment] 2015-12-02 15:00
Hi @rzwitserloot! I narrowed it down to a specific annotation:

`@Getter(onMethod = @__(@JsonProperty(value = "alias")))`

```
CustomPortalDto.java:27: error: cannot find symbol
	@Getter(onMethod = @__(@JsonProperty(value = "alias")))
	                    ^
  symbol:   class __
  location: class CustomPortalDto
CustomPortalDto.java:28: error: cannot find symbol
```

That annotation fails on Java 8 and works on Java 7. That eliminates Gradle out of the equation. Is that a known issue with `@__` ? Can you recommend any alternative or just refactor that code without Lombok?

**Comment by dfernandezm** [comment] 2015-12-02 15:09
I see there is a current open issue relating to this #778

**Comment by thekalinga** [comment] 2017-09-07 08:53
@dfernandezm @rzwitserloot The linked issue is closed in Feb. Can we expect any resolution to this?

**Comment by darioseidl** [comment] 2019-05-02 12:40
Old issue, but since I just stumbled upon it:

It is documented here https://projectlombok.org/features/experimental/onX that for JDK8 a different syntax is needed for `onMethod` etc.

JDK7:
```
  @Getter(onMethod=@__({@Id, @Column(name="unique-id")})) //JDK7
  @Setter(onParam=@__(@Max(10000))) //JDK7
```

JDK8:
```
  @Getter(onMethod_={@Id, @Column(name="unique-id")}) //JDK8
  @Setter(onParam_=@Max(10000)) //JDK8
```

**Closed** 2019-05-02 23:34 UTC
