### ISSUE TITLE
[BUG] StackOverflowError during compilation

### ISSUE THREAD

**Issue by xxDark** [rzwitserloot/lombok#2805] opened 2021-04-03 17:41 UTC
**Describe the bug**
`StackOverflowError` during compilation.

**To Reproduce**
https://paste.implario.dev/nasovuyeze.java

**Expected behavior**
No `StackOverflowError`

**Version info (please complete the following information):**

1.18.20
javac 1.8.0_275

**Comment by xxDark** [comment] 2021-04-03 17:47
[Uage](https://paste.implario.dev/jucoyutexi.java) of local variable for the injector seems to solve the issue.

**Comment by Rawi01** [comment] 2021-04-04 21:04
Duplicate of #1118
As you already figured out the easiest workaround is to split up the long method invocation chain.

**Closed by Rawi01** 2021-04-04 21:04 UTC
