### ISSUE TITLE
Lombok 1.16.22 @EqualsHashCode uses transient field

### ISSUE THREAD

**Issue by mucahitkurt** [rzwitserloot/lombok#1744] opened 2018-06-26 15:14 UTC
Hello,
Lombok 1.16.22 uses both transient and non-transient fields to produce equals and hashCode methods.

I use IntelliJ 2018.1 with lombok plugin.

```
@Getter
@EqualsAndHashCode
public class SomeClass {

    private transient String someTransientField;
    private String someNonTransientField;

}
```

Lombok 1.16.22 produces;
```
public int hashCode() {
        int PRIME = true;
        int result = 1;
        Object $someTransientField = this.getSomeTransientField();
        int result = result * 59 + ($someTransientField == null ? 43 : $someTransientField.hashCode());
        Object $someNonTransientField = this.getSomeNonTransientField();
        result = result * 59 + ($someNonTransientField == null ? 43 : $someNonTransientField.hashCode());
        return result;
    }
```

Lombok 1.16.20 produces;
```
public int hashCode() {
        int PRIME = true;
        int result = 1;
        Object $someNonTransientField = this.getSomeNonTransientField();
        int result = result * 59 + ($someNonTransientField == null ? 43 : $someNonTransientField.hashCode());
        return result;
    }
```

**Comment by janrieke** [comment] 2018-06-26 15:33
Looks like a duplicate of #1724, which is already fixed.

**Closed** 2018-06-26 19:38 UTC
