### ISSUE TITLE
Issue during usage of @NonNull with @SuperBuilder in 1.18.2

### ISSUE THREAD

**Issue by konstantinMinkov** [rzwitserloot/lombok#1862] opened 2018-09-14 12:48 UTC
During the usage of @SuperBuilder I've discovered an issue.

For example:
```
@SuperBuilder
public class Parent {

    private String field;

    @NonNull
    private String notEmptyField;
}
```
```
@SuperBuilder
public class Child extends Parent {

    @NonNull
    private String otherNonNullField;
}
```
I've got an error during maven build:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project back-end: Compilation failure
[ERROR] /C:/Users/Default/Desktop/cinema/back-end/src/main/java/example/Child.java:[6,1] constructor Parent in class example.Parent cannot be applied to given types;
[ERROR] required: example.Parent.ParentBuilder<?,?>
[ERROR] found: no arguments
[ERROR] reason: actual and formal argument lists differ in length
```
In case I remove @NonNull annotation from the field of the Child class everything works as a charm.

**Comment by janrieke** [comment] 2018-09-14 14:12
Duplicate of #1800. Fixed with PR #1820 in edge 1.18.3 and the next release 1.18.4.

**Comment by konstantinMinkov** [comment] 2018-09-14 14:15
@janrieke I think we can leave this PR opened for convenience of other people experiencing this issue?

**Comment by janrieke** [comment] 2018-09-14 16:01
You could give the edge release a try just to make sure you didn't spot a different bug. If it's fixed, you can close it. Other users can still find it using the search.

**Comment by rzwitserloot** [comment] 2019-05-06 20:32
feels like this is fixed :)

**Closed by rzwitserloot** 2019-05-06 20:32 UTC
