### ISSUE TITLE
[BUG] When Lombok is combined with easyexcel, reading Excel files and reflecting them into entities are all null

### ISSUE THREAD

**Issue by wzlstudy** [rzwitserloot/lombok#2527] opened 2020-07-24 08:23 UTC
**Describe the bug**
When Lombok is combined with easyexcel, reading Excel files and reflecting them into entities are all null

**To Reproduce**
The entity class attributes I defined are named after humps. When I use easyexcel to implement the write operation, I find that all the data written are null values, but the get and set methods generated by me can be written to the file normally.
`@Data
public class DataDemo {
    @ExcelProperty("一级分类")
    private String oName;
    @ExcelProperty("二级分类")
    private String tName;
}`

**Expected behavior**
If I use Lombok's @ Data annotation, this is how it works
dataDemo.setOName("dd");
dataDemo.setTName("dd");
But if I use the generated set method, the use is like this
dataDemo.setoame("dd");
dataDemo.settame("dd");
I think it is caused by the difference between the set method generated by @ Data annotation and the method approved by easyexcel
**Version info (please complete the following information):**
 - 1.18.12
 - jdk8

**Additional context**

**Comment by Rawi01** [comment] 2020-07-28 08:49
I think that the problem here is that there are competing "standards" on how to generate getter and setter names in this corner case. See https://github.com/rzwitserloot/lombok/issues/757 for more details. To solve this one you can either rename your fields or write the required getters by hand.

**Comment by rzwitserloot** [comment] 2021-01-02 14:27
Duplicate of #2693

**Closed by rzwitserloot** 2021-01-02 14:27 UTC
