### ISSUE TITLE
Caused by: java.lang.LinkageError: loader constraint violation: when resolving method "lombok.launch.PatchFixesHider$Transform.transform_swapped

### ISSUE THREAD

**Issue by kppgs** [rzwitserloot/lombok#1291] opened 2017-02-07 10:45 UTC
This happens in Eclipse (Version 4.6.2) and Lombok 1.16.12:
```
Error while compiling Jasper reports (com.alexnederlof:jasperreports-plugin:1.6:jasper:default:process-sources)

org.apache.maven.plugin.MojoExecutionException: Error while compiling Jasper reports
	at com.alexnederlof.jasperreport.JasperReporter.executeTasks(JasperReporter.java:238)
	at com.alexnederlof.jasperreport.JasperReporter.execute(JasperReporter.java:138)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:331)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl$11.call(MavenImpl.java:1362)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl$11.call(MavenImpl.java:1)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1360)
	at org.eclipse.m2e.core.project.configurator.MojoExecutionBuildParticipant.build(MojoExecutionBuildParticipant.java:52)
	at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.build(MavenBuilderImpl.java:137)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:172)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:1)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1$1.call(MavenBuilder.java:115)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1.call(MavenBuilder.java:105)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:86)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:200)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.util.concurrent.ExecutionException: java.lang.LinkageError: loader constraint violation: when resolving method "lombok.launch.PatchFixesHider$Transform.transform_swapped(Lorg/eclipse/jdt/internal/compiler/ast/CompilationUnitDeclaration;Lorg/eclipse/jdt/internal/compiler/parser/Parser;)V" the class loader (instance of org/codehaus/plexus/classworlds/realm/ClassRealm) of the current class, org/eclipse/jdt/internal/compiler/parser/Parser, and the class loader (instance of lombok/launch/ShadowClassLoader) for the method's defining class, lombok/launch/PatchFixesHider$Transform, have different Class objects for the type org/eclipse/jdt/internal/compiler/ast/CompilationUnitDeclaration used in the signature
	at java.util.concurrent.FutureTask.report(Unknown Source)
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at com.alexnederlof.jasperreport.JasperReporter.checkForExceptions(JasperReporter.java:245)
	at com.alexnederlof.jasperreport.JasperReporter.executeTasks(JasperReporter.java:230)
	... 33 more
Caused by: java.lang.LinkageError: loader constraint violation: when resolving method "lombok.launch.PatchFixesHider$Transform.transform_swapped(Lorg/eclipse/jdt/internal/compiler/ast/CompilationUnitDeclaration;Lorg/eclipse/jdt/internal/compiler/parser/Parser;)V" the class loader (instance of org/codehaus/plexus/classworlds/realm/ClassRealm) of the current class, org/eclipse/jdt/internal/compiler/parser/Parser, and the class loader (instance of lombok/launch/ShadowClassLoader) for the method's defining class, lombok/launch/PatchFixesHider$Transform, have different Class objects for the type org/eclipse/jdt/internal/compiler/ast/CompilationUnitDeclaration used in the signature
	at org.eclipse.jdt.internal.compiler.parser.Parser.endParse(Parser.java:8681)
	at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:9715)
	at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:9933)
	at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:9890)
	at org.eclipse.jdt.internal.compiler.parser.Parser.dietParse(Parser.java:8454)
	at org.eclipse.jdt.internal.compiler.Compiler.internalBeginToCompile(Compiler.java:718)
	at org.eclipse.jdt.internal.compiler.Compiler.beginToCompile(Compiler.java:383)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:428)
	at net.sf.jasperreports.engine.design.JRJdtCompiler.compileUnits(JRJdtCompiler.java:173)
	at net.sf.jasperreports.engine.design.JRAbstractCompiler.compileReport(JRAbstractCompiler.java:212)
	at net.sf.jasperreports.engine.JasperCompileManager.compile(JasperCompileManager.java:357)
	at net.sf.jasperreports.engine.JasperCompileManager.compileToStream(JasperCompileManager.java:326)
	at net.sf.jasperreports.engine.JasperCompileManager.compileToStream(JasperCompileManager.java:309)
	at net.sf.jasperreports.engine.JasperCompileManager.compileReportToStream(JasperCompileManager.java:587)
	at com.alexnederlof.jasperreport.CompileTask.call(CompileTask.java:75)
	at com.alexnederlof.jasperreport.CompileTask.call(CompileTask.java:34)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by rspilker** [comment] 2017-02-09 21:55
Possibly this is fixed in 1.16.14, which is scheduled to be release within a few days. Can you test this?

**Comment by rzwitserloot** [comment] 2017-02-13 21:06
I think this is the same as #1293

**Comment by rzwitserloot** [comment] 2017-02-13 23:24
Duplicate of #1281

**Closed by rzwitserloot** 2017-02-13 23:24 UTC
