### ISSUE TITLE
@Builder annotation lose field default value

### ISSUE THREAD

**Issue by gardenias** [rzwitserloot/lombok#1165] opened 2016-07-28 02:21 UTC
``` java
public class BuilderAnnotationTest {

    @Test
    public void defalutValue() throws Exception {
        assertThat(Entity.builder().build().isSingle()).isTrue();
    }
}

@Getter
@Builder
class Entity{
    private String name;
    private boolean single = true;
}
```

**Comment by Maaartinus** [comment] 2016-07-28 03:52
Duplicate of #916. There's a workaround

    @Getter
    @Builder(toBuilder=true)
    @AllArgsConstructor
    @NoArgsConstructor(access=AccessLevel.PRIVATE)
    public class Entity {
        public static EntityBuilder builder() {
            return PROTOTYPE.toBuilder();
        }
    
        private static final Entity PROTOTYPE = new Entity();
    
        private String name;
        private boolean single = true;
    }

**Comment by kishaningithub** [comment] 2017-07-20 04:49
This also works
```java
public class BuilderAnnotationTest {

    @Test
    public void defalutValue() throws Exception {
        assertThat(new Entity().toBuilder().build().isSingle()).isTrue(); // note the "new" here
    }
}

@Getter
@Builder(toBuilder = true)
class Entity{
    private String name;
    private boolean single = true;
}
```

**Comment by rzwitserloot** [comment] 2018-10-15 19:55
Use `@Builder.Default` to fix this problem.

**Closed by rzwitserloot** 2018-10-15 19:55 UTC
