### ISSUE TITLE
[BUG] Lombok disables itself when building with JDK 14

### ISSUE THREAD

**Issue by friendlyanon** [rzwitserloot/lombok#2501] opened 2020-06-26 13:35 UTC
**Describe the bug**
Building with JDK 14 shows the following error:
```
warning: You aren't using a compiler supported by lombok, so lombok will not work and has been disabled.
  Your processor is: org.gradle.api.internal.tasks.compile.processing.IncrementalProcessingEnvironment
  Lombok supports: OpenJDK javac, ECJ
```

**To Reproduce**
1. Use AdoptOpenJDK 14
2. Generate a brand new project with Spring Initializr that uses Lombok
3. `gradlew bootRun`

**Expected behavior**
Build without errors.

**Version info (please complete the following information):**
 - Lombok latest
 - javac 14.0.1

**Additional context**
I have attached a demo project that reproduces the error in JDK 14 but not in JDK 11.
[demo.zip](https://github.com/rzwitserloot/lombok/files/4837202/demo.zip)

**Comment by Rawi01** [comment] 2020-07-21 23:25
I can not reproduce the issue. I also tried different java versions, including the latest AdoptOpenJDK version and verified that lombok works by adding some annotations. Can you provide some more details for example a full log of the build or an docker image that can be used to reproduce it?

Disclaimer: I'm not a project owner.

**Comment by mschaaf** [comment] 2020-07-22 07:37
@Rawi01 have you tried the attached demo project in the demo.zip file? I can reproduce it with this project.

**Comment by Rawi01** [comment] 2020-07-22 08:05
@mschaaf Yes, I tried the demo project and also create a new project using Spring Initializr. I tried `AdoptOpenJDK 14.0.1+7` and `AdoptOpenJDK 14.0.2+12`.

**Comment by mschaaf** [comment] 2020-07-22 10:43
My steps to reproduce:

1. unpack the demo.zip to a folder called demo
2. change into that folder
3. install `sdk install java 14.0.1.j9-adpt`
4. use `sdk use java 14.0.1.j9-adpt`
4. call `./gradlew clean`
4. call `./gradlew bootRun`

Or with openjdk

1. unpack the demo.zip to a folder called demo
2. change into that folder
3. install `sdk install java 14.0.2-open`
4. use `sdk use java 14.0.2-open`
4. call `./gradlew clean`
4. call `./gradlew bootRun`

**Comment by Rawi01** [comment] 2020-07-22 11:13
I tried to run this in a new ubuntu docker container but it requires two changes: 
- `14.0.1.j9-adpt` is no longer available, I had to use `14.0.2.j9-adpt`
- I had to add `chmod +x gradlew` to run it

After that both JDKs work without any problems.

**Comment by FrogDevelopper** [comment] 2020-07-27 08:41
I have exactly the same issue when using
* java version _14.0.2.j9-adpt_
* gradle version _6.5.1_
* gradle plugin io.freefair.lombok version _5.1.0_

building by IntelliJ or command line lead to the same error message:
> \> Task :compileJava FAILED
warning: You aren't using a compiler supported by lombok, so lombok will not work and has been disabled.
  Your processor is: org.gradle.api.internal.tasks.compile.processing.IncrementalProcessingEnvironment
  Lombok supports: OpenJDK javac, ECJ

**Comment by Rawi01** [comment] 2020-07-27 11:05
I finally managed to reproduce this one in a docker container. On my normal machine the build crashes which is a OpenJ9 related bug and fixed in the latest edge version. Adding the [edge version](https://projectlombok.org/download-edge) fixed both builds. Can you confirm that this solves the problem?

**Comment by friendlyanon** [comment] 2020-07-27 13:10
I can confirm that the edge version builds on AdoptOpenJDK 14.0.2 with the attached project.

**Comment by doublefx** [comment] 2020-10-02 17:11
Note that it happens to me with JDK 11.

I'm using IntellIJ 2020.3 EAP

java: You aren't using a compiler supported by lombok, so lombok will not work and has been disabled.
  Your processor is: com.sun.proxy.$Proxy27
  Lombok supports: OpenJDK javac, ECJ

**Comment by Vyacheslav-Lapin** [comment] 2020-10-02 18:14
Same problem

**Comment by mplushnikov** [comment] 2020-10-03 20:07
@doublefx IntelliJ issue is handled by #2592

**Comment by mschaaf** [comment] 2020-12-22 14:55
Is it possible to close this as with the latest AdoptOpenJDK and version Lombok v1.18.16 this is fixed for me?

**Comment by rzwitserloot** [comment] 2020-12-22 16:11
Thanks to @Rawi01 for doing a lot of the work on this one. The error has multiple causes; As per @mplushnikov 's suggestion, let's discuss the one caused by the Processor type being `com.sun.proxy.$Proxy27` in issue #2592, and leave this one for the gradlew issue. We've fixed that in .16, and from what I read here, that fix is working. Let me know if 1.18.16 and/or edge causes this issue __and__ `org.gradle.api.internal.tasks.compile.processing.IncrementalProcessingEnvironment` is reported as the processor, so that I can re-open.

**Closed by rzwitserloot** 2020-12-22 16:11 UTC
