### ISSUE TITLE
jdk10 compile error

### ISSUE THREAD

**Issue by lilaizhencn** [rzwitserloot/lombok#1621] opened 2018-03-21 12:24 UTC
<dependency> <groupId>org.projectlombok</groupId> <artifactId>lombok</artifactId> <version>1.16.20</version> </dependency>

➜ ~ java -version java version "10" 2018-03-20 Java(TM) SE Runtime Environment 18.3 (build 10+46) Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10+46, mixed mode)

mvn spring-boot:run

Fatal error compiling: java.lang.ExceptionInInitializerError: com.sun.tools.javac.code.TypeTags

**Comment by krzyk** [comment] 2018-03-21 12:44
looks like a duplicate of #1572

**Comment by rspilker** [comment] 2018-04-30 20:17
Already fixed in the [edge release](https://projectlombok.org/download-edge).

**Closed by rspilker** 2018-04-30 20:17 UTC

**Comment by cesartl** [comment] 2018-05-09 07:30
Is it possible to get the edge release from Maven?
Do you know when a version with this fix will be released?

**Comment by barmic** [comment] 2018-05-09 07:39
You can install the jar in your local repository with command:

```
mvn install:install-file -Dfile=lombok-edge.jar -DgroupId=org.projectlombok -DartifactId=lombok -Dversion=edge -Dpackaging=jar
```

And use it with:

```
<dependency>
	<groupId>org.projectlombok</groupId>
	<artifactId>lombok</artifactId>
	<version>edge</version>
</dependency>
```

This version isn't in central repositories.

**Comment by cesartl** [comment] 2018-05-09 07:41
yes I know but I'm more concerned about our build tool which uses Artifactory, and for some reason I'm not able to able upload the artifact there. That's something which I will check with Artifactory but was wondering if there was a workaround.
Is there a planned date for a next release?
