### ISSUE TITLE
 Use @Data  and @Builder at same time cause compile error

### ISSUE THREAD

**Issue by veryyoung** [rzwitserloot/lombok#1084] opened 2016-04-13 12:14 UTC
Solution:

append `@NoArgsConstructor` and `@AllArgsConstructor` 

Is this a bug?

**Comment by rspilker** [comment] 2016-05-11 22:42
I just created tests for this and cannot reproduce the problem. Can you have a look at our test files?

https://github.com/rzwitserloot/lombok/blob/master/test/transform/resource/before/BuilderValueData.java
https://github.com/rzwitserloot/lombok/blob/master/test/transform/resource/after-delombok/BuilderValueData.java
https://github.com/rzwitserloot/lombok/blob/master/test/transform/resource/after-ecj/BuilderValueData.java

What compiler do you use? Eclipse, mvn, javac? What version?

What happens if you try to compile the [after-delombok file](https://github.com/rzwitserloot/lombok/blob/master/test/transform/resource/after-delombok/BuilderValueData.java) in your environment?

**Comment by askoning** [comment] 2017-02-24 15:30
Closing as we cannot reproduce this, and no feedback has been given.

**Closed by askoning** 2017-02-24 15:30 UTC
