### ISSUE TITLE
Enum fields excluded from constructor when sibling fields annotated with @NotNull

### ISSUE THREAD

**Issue by johno1985** [rzwitserloot/lombok#982] opened 2015-12-01 17:24 UTC
Given the following enum:

```
public enum MyEnum {
     A, B, C;
}
```
and the following class:
```
@Data
public class MyClass {
    @NonNull
    private String x;
    @NonNull
    private String y;
    private MyEnum z = MyEnum.A;
}
```

When deserialising a json string into MyClass, the value of z is somehow set to null. When removing the two @NonNull annotations, the default value was preserved

**Comment by rspilker** [comment] 2015-12-06 21:42
I think the problem is that `@Data` generated the `@RequiredArgsConstructor`, that only has parameters for `final` and for `@NonNull` fields. Removing `@NonNull` from the other fields results in only the default constructor.

Adding `@AllArgsConstructor` probably fixes your problem. 

Please let us know if this solves your problem.

**Comment by rspilker** [comment] 2016-05-11 23:09
Closing this issue since the reporter did not respond.

**Closed by rspilker** 2016-05-11 23:09 UTC
Labels: parked
