### ISSUE TITLE
NullPointerException when using ToBuilder and Singular on List-based Property

### ISSUE THREAD

**Issue by HartmutLuttermann** [rzwitserloot/lombok#1483] opened 2017-10-04 11:04 UTC
Having following class definition
```
@Value
@Builder(toBuilder = true)
public class ValueObject{

    @Singular(value = "value")
    private List<String> values;
}
```
and using following statement 
```
new ValueObject(null).toBuilder();
```
throws NullPointerException in method toBuilder()
```
java.lang.NullPointerException
	at java.util.ArrayList.addAll(ArrayList.java:577)
	at <package>.ValueObject$ValueObjectBuilder.values(ValueObject.java:10)
```
In my opinion this is an error in the implementation of the setter-method of the ValueObjectBuilder. A non-null-check only will fix this:
```
public ValueObject.ValueObjectBuilder values(final Collection<? extends String> values) {
            if (this.values == null) this.values = new ArrayList<String>();
           // added: check on non-null values
            if (values != null)
                  this.values.addAll(values);
            return this;
        }
```

**Comment by brokenbeatnik** [comment] 2017-12-11 23:32
I'm also seeing this issue.

**Comment by oyku-gencay** [comment] 2018-01-16 11:43
Same here. I've got a private constructor annotated with @Builder with toBuilder true.

**Comment by rzwitserloot** [comment] 2018-10-15 19:09
Duplicate of #1324 – the suggested fix is not acceptable; calling .foos(null) silently doing nothing is not a sound plan. A fix for this problem is forthcoming.

**Closed by rzwitserloot** 2018-10-15 19:09 UTC
Labels: duplicate
