### ISSUE TITLE
Generate static field name

### ISSUE THREAD

**Issue by lludwa** [rzwitserloot/lombok#1484] opened 2017-10-04 11:40 UTC
JPA Metamodel Generator generates Metamodel (e.g. SingularAttribute) for each Entity field.
But sometimes you just want to use a field name in string. More often you want to use it not on a class which is not Entity (DTO for example).

That is why I’d suggest ```@GenerateFieldName``` annotation where one has possibility to create static access to the variable name. For example:

```
@GenerateFieldName
private Integer myVariable;

…
assertEquals(MyClass.FIELD_MY_VARIABLE, "myVariable")
```

It could be used anywhere where you need to bind some value to specific field using reflection or beanutils

**Comment by Maaartinus** [comment] 2017-10-04 22:19
Duplicate of #1240 and #1268. Nearly one year later; unfortunately, there's no progress on this.

**Comment by vadipp** [comment] 2018-10-26 04:36
https://github.com/rzwitserloot/lombok/pull/46 was merged, so this issue should be closed, imo.

**Closed** 2021-02-02 16:31 UTC
