### ISSUE TITLE
Bug report: generate getter/setter method bug

### ISSUE THREAD

**Issue by ydq** [rzwitserloot/lombok#1454] opened 2017-08-12 08:06 UTC
The standard Javabean specification specifies the getter / setter method as follows:

uName  -> getuName / setuName

But Lombok generated the code is getUName / setUName

Eclipse: Oxygen Release (4.7.0)
Lombok: v1.16.18

![image](https://user-images.githubusercontent.com/8097340/29239217-d3f884b6-7f7b-11e7-9840-4ed47dfe841b.png)

**Comment by o-pikozh** [comment] 2017-08-14 13:34
I what place does [JavaBeans specification](http://download.oracle.com/otndocs/jcp/7224-javabeans-1.01-fr-spec-oth-JSpec/) say that a getter should be named `getuName` instead of `getUName`?

**Comment by cardamon** [comment] 2017-08-14 13:54
Certainly not in section 8.3.1 :wink:

**Comment by Maaartinus** [comment] 2017-08-14 13:56
Duplicate of #1453, #757 and many others.

Javabeans is fubared. Some long time ago I was unhappy about Lombok mistreating my "uShaped" property and wrote manual etters als workaround. IIRC it didn't work either, because some other tool didn't understand it in the opposite direction (`setuShaped -> uShaped`), so I ended using "shapedAsU" instead. :roll_eyes:

**Comment by o-pikozh** [comment] 2017-08-14 14:16
Yep, = #757.

**Comment by ydq** [comment] 2017-08-15 03:13
@o-pikozh  @cardamon 

At least jsp think so...

![lombok1](https://user-images.githubusercontent.com/8097340/29300658-5d0844a6-81a9-11e7-9427-f395dc978212.jpg)


I use Eclipse to generate getter / setter to keep it correct

![lombok2](https://user-images.githubusercontent.com/8097340/29300706-b7142d02-81a9-11e7-9fed-9d0d8119259d.jpg)

Then the jsp show the correct results

![lombok3](https://user-images.githubusercontent.com/8097340/29300707-b9adbd8a-81a9-11e7-9087-091cbb8a2ef1.jpg)

**Comment by o-pikozh** [comment] 2017-08-15 08:38
@ydq 

I already see that it indirectly comes from § 8.8 “Capitalization of inferred names”:
> We provide a method `Introspector.decapitalize` which implements this conversion rule.
— and `Introspector.decapitalize` works in this way (`aBcd` ↔ `getaBcd`).

Still, you should read [the whole discussion](//groups.google.com/d/topic/project-lombok/c9WKYhlfe8k/discussion). And not duplicate [the original report](757). Probably it will remain "won't fix".

**Closed** 2017-08-21 02:57 UTC

**Comment by rzwitserloot** [comment] 2021-01-02 14:29
Duplicate of #2693
