### ISSUE TITLE
[FEATURE] Customize prefix of boolean getter

### ISSUE THREAD

**Issue by straurob** [rzwitserloot/lombok#2239] opened 2019-09-16 06:52 UTC
Let's say I have the following class:

```
@Data
public class MyEntity {
  private boolean contactform;
}
```

Lombok then provides the getter method `isContactform()`. In some cases I'd like this method to be called `hasContactform()`.

Could we provide a feature/property which allows changing the prefix for a specific field?

**Comment by Maaartinus** [comment] 2019-09-16 21:04
Duplicate of #836 (a denied request).

I have a strong opinion on the naming (which doesn't matter as I'm not a lombok project member). Nonetheless, you may want to read my https://github.com/rzwitserloot/lombok/issues/836#issuecomment-501886584.

In any case, I'd suggest to call the variable `hasContactform` (or alike) as it's a boolean rather than a form.

**Closed** 2019-10-01 19:11 UTC

**Comment by IgorArnaut** [comment] 2025-04-13 18:45
Why is denied? Let us customize prefixes to make method names make more sense.
