### ISSUE TITLE
Feature Request JavaFX8 Properties

### ISSUE THREAD

**Issue by MrH17** [rzwitserloot/lombok#1162] opened 2016-07-27 07:40 UTC
Hello I would like to have some additional Annotations for JavaFX8 Properties.

Something like

```
@PropertyGetter
@PropertySetter
@Property
private StringProperty test;
```

which generates

```
public String getTest(){
    return test.get();
}
public void setTest(String test){
    test.set(test);
}
public StringProperty testProperty(){
    return test;
}
```

it would be nice to have that for all implementors of the [Property<T> Interface](https://docs.oracle.com/javase/8/javafx/api/javafx/beans/property/Property.html)
An additionaly usefull thing would be to combine these three Annotations in @Properties

I hope you could do that. I love lombok and don't want to go back to writing all my getters & setters by hand just because of using Properties.

**Comment by danilovEY** [comment] 2017-04-03 11:01
Actually many people asked to create various annotation like Getter/Setter, but more functional. May be make any opportunity describe how to do it get or set? something like this :
`
enum MyEnum {A, B, C}

public class Test {
    @Setter(MyEnumSetter.class)
    private MyEnum myEnum;

    public static void main(String[] args) {
        new Test().setMyEnum("A");
    }
}

public class MyEnumSetter implements SetterHandle<Test, String> {
    public void handleSetter(Test obj, Field myEnum, String arg) {
        myEnum.set(obj, MyEnum.valueOf(arg));
    }
}

interface SetterHandle<O, A> {
    void handleSetter(O obj, Field field, A arg);
}
`

**Comment by omega09** [comment] 2017-04-03 20:06
Duplicate of #1222

**Comment by rspilker** [comment] 2019-05-21 19:45
Duplicate

**Closed by rspilker** 2019-05-21 19:45 UTC
