### ISSUE TITLE
Wish we could have @EnumId in lombok

### ISSUE THREAD

**Issue by demongaorui** [rzwitserloot/lombok#1375] opened 2017-05-02 22:04 UTC
In lombok-pg, there is [@EnumId](https://github.com/peichhorn/lombok-pg/wiki/%40EnumId) annotation, feels very useful. While lombok-pg stop updating about 4 years ago. And it's told that lombok-pg does not work well with java 8. So I wish we could have @EnumId in lombok

**Comment by rspilker** [comment] 2017-05-15 21:03
Duplicate of #706

**Closed by rspilker** 2017-05-15 21:03 UTC
Labels: duplicate
