### ISSUE TITLE
[BUG] @SuperBuilder with generic with inner static class produces CE

### ISSUE THREAD

**Issue by agackovka** [rzwitserloot/lombok#2262] opened 2019-10-18 07:07 UTC
**Describe the bug**
Base class has generic parameter
Parent class extends Base class with any inner static class generic
get Compile Error 

> Error:(5, 1) java: wrong number of type arguments; required 3

**To Reproduce**
```package reproducing;

import lombok.experimental.SuperBuilder;

@SuperBuilder
public class Parent extends Base<Parent.SomeInnerStaticClass> {

    private String parentString;

    public static class SomeInnerStaticClass { }
}

@SuperBuilder
class Base<T> {
    private final String baseString;
}
```

**Expected behavior**
Should compile

**Version info (please complete the following information):**
 - Lombok version 1.18.10
 - Platform 1.8.201

**Describe the bug**
Maybe it's an Intllij Idea problem, but if you use not inner static class it works fine

**Comment by janrieke** [comment] 2019-10-18 10:59
Could you try it without IntelliJ, i.e. using maven/gradle/javac?

**Comment by Lekanich** [comment] 2019-10-27 09:19
It's reproduced with maven.

**Comment by Lekanich** [comment] 2019-10-27 12:21
The root cause in "Base" class as I see. Lombok generate extends clause without knowledge about generics of Base class. That's why it generates "extends Base.BaseBuilder<C, B>" instead "extends Base.BaseBuilder<Parent.SomeInnerStaticClass, C, B>"


```java
import lombok.experimental.SuperBuilder;

@SuperBuilder()
public class Parent extends Base<Parent.SomeInnerStaticClass> {
    private String parentString;

    public static class SomeInnerStaticClass {

        public SomeInnerStaticClass() {
            super();
        }
    }

    @java.lang.SuppressWarnings("all")
    public static abstract class ParentBuilder<C extends Parent, B extends ParentBuilder<C, B>> extends Base.BaseBuilder<C, B> {
        @java.lang.SuppressWarnings("all")
        private String parentString;

        @java.lang.Override()
        @java.lang.SuppressWarnings("all")
        protected abstract B self();

        @java.lang.Override()
        @java.lang.SuppressWarnings("all")
        public abstract C build();

        @java.lang.SuppressWarnings("all")
        public B parentString(final String parentString) {
            this.parentString = parentString;
            return self();
        }

        @java.lang.Override()
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "Parent.ParentBuilder(super=" + super.toString() + ", parentString=" + this.parentString + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    private static final class ParentBuilderImpl extends ParentBuilder<Parent, ParentBuilderImpl> {

        @java.lang.SuppressWarnings("all")
        private ParentBuilderImpl() {
        }

        @java.lang.Override()
        @java.lang.SuppressWarnings("all")
        protected ParentBuilderImpl self() {
            return this;
        }

        @java.lang.Override()
        @java.lang.SuppressWarnings("all")
        public Parent build() {
            return new Parent(this);
        }
    }

    @java.lang.SuppressWarnings("all")
    protected Parent(final ParentBuilder<?, ?> b) {
        super(b);
        this.parentString = b.parentString;
    }

    @java.lang.SuppressWarnings("all")
    public static ParentBuilder<?, ?> builder() {
        return new ParentBuilderImpl();
    }
}
@SuperBuilder()
class Base<T> {
    private final String baseString;

    @java.lang.SuppressWarnings("all")
    public static abstract class BaseBuilder<T, C extends Base<T>, B extends BaseBuilder<T, C, B>> {
        @java.lang.SuppressWarnings("all")
        private String baseString;

        @java.lang.SuppressWarnings("all")
        protected abstract B self();

        @java.lang.SuppressWarnings("all")
        public abstract C build();

        @java.lang.SuppressWarnings("all")
        public B baseString(final String baseString) {
            this.baseString = baseString;
            return self();
        }

        @java.lang.Override()
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "Base.BaseBuilder(baseString=" + this.baseString + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    private static final class BaseBuilderImpl<T> extends BaseBuilder<T, Base<T>, BaseBuilderImpl<T>> {

        @java.lang.SuppressWarnings("all")
        private BaseBuilderImpl() {
        }

        @java.lang.Override()
        @java.lang.SuppressWarnings("all")
        protected BaseBuilderImpl<T> self() {
            return this;
        }

        @java.lang.Override()
        @java.lang.SuppressWarnings("all")
        public Base<T> build() {
            return new Base<T>(this);
        }
    }

    @java.lang.SuppressWarnings("all")
    protected Base(final BaseBuilder<T, ?, ?> b) {
        this.baseString = b.baseString;
    }

    @java.lang.SuppressWarnings("all")
    public static <T>BaseBuilder<T, ?, ?> builder() {
        return new BaseBuilderImpl<T>();
    }
}
```

**Comment by rzwitserloot** [comment] 2019-12-19 02:30
This is fixed via #2278, thanks @Lekanich!

Will be in next stable.

**Closed by rzwitserloot** 2019-12-19 02:30 UTC

**Comment by Vyacheslav-Lapin** [comment] 2020-01-13 15:44
Is it in version "edge-SNAPSHOT" (https://projectlombok.org/download-edge) already? With that version I have this problem too... :(

**Comment by janrieke** [comment] 2020-01-19 16:33
Since 2020-01-15, it is.
