### ISSUE TITLE
Getter-method-name of Boolean-object (wrapper) is "getBool" and not "isBool"

### ISSUE THREAD

**Issue by ImpulseTheFox** [rzwitserloot/lombok#1879] opened 2018-10-01 14:11 UTC
Generating a getter of a boolean (primitive) generates a getter-method with the name "isBool".
But generating a getter of a Boolean-object (wrapper) generates a getter-method with the name "getBool".

It looks like the Boolean-object (wrapper) is not recognized as a boolean and thus not affected by the special boolean "is"-prefix. Please consider this.

**Comment by Maaartinus** [comment] 2018-10-01 14:59
Duplicate of [#382](https://github.com/rzwitserloot/lombok/issues/382#issuecomment-121374395). Lombok is javabeans-compliant in this respect.

I simply added the line
```
lombok.getter.noIsPrefix=true
```
to `lombok.config` and ignore the whole "is/get" mess. Not javabeans-compliant, but logical. YMMV.

Another possibility is to use
```
lombok.accessors.fluent=true
lombok.accessors.chain=true
```
and get fluent getters no "is/get" prefix at all.

There's no way how to get the "is" prefix for the `Boolean` wrapper.

**Comment by ImpulseTheFox** [comment] 2018-10-01 15:34
Alright, because I actually wanted to do the opposite. I want the
"is"-prefix.

**Comment by rspilker** [comment] 2018-10-08 20:13
As @Maaartinus explained, what you want is not according to the beanspec.

**Closed** 2018-10-08 20:13 UTC

**Comment by adispennette** [comment] 2018-10-29 22:29
@rspilker 
>  what you want is not according to the beanspec

But The bean spec says:
> In addition, for boolean properties, we allow a getter method to match the pattern:
> public boolean is<PropertyName>();
> This “is<PropertyName>” method may be provided instead of a “get<PropertyName>” meth-od, or > it may be provided in addition to a “get<PropertyName>” method.In either case, if the 
> “is<PropertyName>” method is present for a boolean property then we will use the 
> “is<PropertyName>” method to read the property value

**Comment by Maaartinus** [comment] 2018-10-30 20:51
@adispennette In case you mean `boolean`, then note that Lombok by default uses the "is" prefix, which is correct according to the crapspec. In case you mean `Boolean`, then look at the last line of [JDK-8028714](https://bugs.openjdk.java.net/browse/JDK-8028714) saying "Note that the Boolean class is not boolean".
