### ISSUE TITLE
ant intellij - failing

### ISSUE THREAD

**Issue by nagkumar** [rzwitserloot/lombok#2309] opened 2019-12-10 11:37 UTC
ant target IntelliJ failing to create IntelliJ project 

c:\temp\lombok-master\build.xml:395: java.lang.IllegalStateException: impossible to get artifacts when data has not been loaded. IvyNode = org.eclipse.platform#org.eclipse.core.filesystem;[1.3.0,2.0.0)
        at org.apache.ivy.core.resolve.IvyNode.getArtifacts(IvyNode.java:811)
        at com.zwitserloot.ivyplusplus.intellij.BuildIntellijProject.generateLibraryXml(Unknown Source)
        at com.zwitserloot.ivyplusplus.intellij.BuildIntellijProject.doExecute(Unknown Source)
        at org.apache.ivy.ant.IvyTask.execute(IvyTask.java:271)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
        at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
        at org.apache.tools.ant.Task.perform(Task.java:350)
        at org.apache.tools.ant.Target.execute(Target.java:449)
        at org.apache.tools.ant.Target.performTasks(Target.java:470)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1391)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1254)
        at org.apache.tools.ant.Main.runBuild(Main.java:830)
        at org.apache.tools.ant.Main.startAnt(Main.java:223)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)

**Comment by rzwitserloot** [comment] 2020-01-08 00:33
Duplicate of #2314 - and addressed.

**Closed by rzwitserloot** 2020-01-08 00:33 UTC

**Comment by rzwitserloot** [comment] 2020-02-04 14:05
Fixed (duplicate of issue 1956)
