### ISSUE TITLE
[BUG] Lombok generated code not recognized by eclipse

### ISSUE THREAD

**Issue by prash1981** [rzwitserloot/lombok#2315] opened 2019-12-17 21:19 UTC
eclipse - 2019-09 R + maven + m2e-apt
lombok - 1.18.6
javac version - 13.0.1

I installed lombok using maven, through eclipse and i after installing the m2e-apt, i can see the lombok jar file in the javac annotation processor list. I can also see that auto-complete and searching for references/declarations of the generated getter/setter/builder methods seem to work.

I also installed (the maven resolved) lombok.jar into eclipse by executing the jar file.

However eclipse keeps showing a "quick fix" tool tip where ever the lombok generated methods are used.

Compilation/packaging using maven works fine.
I also don't see anything getting generated in target/generated-sources/annotations (i have not turned on any sort of source-generation in maven). Should this be happening though, for my issue to go away ?

Note, though my project is a multi-module maven project. This issue seems to be happening even within the same project and even inside the same package 

Attaching snapshots.
issue-1 -: The location where the quick tips are shown (usage/reference of the getter/setter functions)
issue-2 -: Shows that the getters/setters are actually shown in the eclipse outline view

![lombok-eclipse-issue-2](https://user-images.githubusercontent.com/26942885/71034863-2936d580-20cf-11ea-85d4-0e8487261664.jpg)
![Lombok-eclipse-issue-1](https://user-images.githubusercontent.com/26942885/71034872-2d62f300-20cf-11ea-9c52-8b623faadb35.jpg)

**Comment by rzwitserloot** [comment] 2020-01-08 00:20
lombok does not generate anything there, and you should not include lombok as an annotation processor in your eclipse project. Just put lombok.jar on the project classpath and make sure lombok is installed in eclipse (you can check in the about dialog, in the text, at the very end, it'll say 'lombok version {Version} is installed.'

The getters are there, and you did not mention what the quick fixes are trying to tell you.

Given that this bug report therefore doesn't say anything tangible I'm going to close it, if after the above you still have issues, please file a new bug report and include the precise actual _ERROR_ you get (from the problems box); screenshots are useless; if I cannot reproduce it on my own machine I cannot fix these bugs.

**Closed by rzwitserloot** 2020-01-08 00:20 UTC
