### ISSUE TITLE
[BUG] Eclipse: java.lang.NullPointerException: Cannot invoke "org.eclipse.jdt.internal.compiler.CompilationResult.getCompilationUnit()" because "unitResult" is null

### ISSUE THREAD

**Issue by jerith666** [rzwitserloot/lombok#2788] opened 2021-03-24 12:44 UTC
**Describe the bug**
Eclipse fails with the error in the summary when building with `-javaagent:lombok.jar`.

**To Reproduce**
I don't have a SSCCE.  I've added `-javaagent:lombok.jar` to my `eclipse.ini`, and when loading a workspace containing hundreds of projects, I get the following error.  Eclipse doesn't give me any indication of *which* project in the workspace it was compiling when this happened, so I'm not sure how to narrow it down.  :-(

```
!SESSION 2021-03-24 08:24:15.523 -----------------------------------------------
eclipse.buildId=4.18.0.I20201202-1800
java.version=15.0.1
java.vendor=N/A
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64

!ENTRY org.eclipse.core.resources 2 10035 2021-03-24 08:24:19.782
!MESSAGE The workspace exited with unsaved changes in the previous session; refreshing workspace to recover changes.

!ENTRY org.eclipse.core.resources 4 2 2021-03-24 08:25:08.011
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.core.resources".
!STACK 0
java.lang.NullPointerException: Cannot invoke "org.eclipse.jdt.internal.compiler.CompilationResult.getCompilationUnit()" because "unitResult" is null
        at org.eclipse.jdt.internal.compiler.problem.ProblemHandler.handle(ProblemHandler.java:148)
        at org.eclipse.jdt.internal.compiler.problem.ProblemHandler.handle(ProblemHandler.java:229)
        at org.eclipse.jdt.internal.compiler.problem.ProblemReporter.handle(ProblemReporter.java:2624)
        at org.eclipse.jdt.internal.compiler.problem.ProblemReporter.nonStaticAccessToStaticMethod(ProblemReporter.java:7169)
        at lombok.eclipse.agent.PatchExtensionMethod$PostponedNonStaticAccessToStaticMethodError.fire(PatchExtensionMethod.java:154)
        at lombok.eclipse.agent.PatchExtensionMethod.resolveType(PatchExtensionMethod.java:371)
        at jdk.internal.reflect.GeneratedMethodAccessor55.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at lombok.launch.PatchFixesHider$Util.invokeMethod(PatchFixesHider.java:126)
        at lombok.launch.PatchFixesHider$ExtensionMethod.resolveType(PatchFixesHider.java:308)
        at org.eclipse.jdt.internal.compiler.ast.MessageSend.resolveType(MessageSend.java:1000)
        at org.eclipse.jdt.internal.compiler.ast.Expression.resolve(Expression.java:1113)
        at org.eclipse.jdt.internal.compiler.ast.Block.resolve(Block.java:131)
        at org.eclipse.jdt.internal.compiler.ast.IfStatement.resolveIfStatement(IfStatement.java:282)
        at org.eclipse.jdt.internal.compiler.ast.IfStatement.resolve(IfStatement.java:308)
        at org.eclipse.jdt.internal.compiler.ast.Block.resolve(Block.java:131)
        at org.eclipse.jdt.internal.compiler.ast.IfStatement.resolveIfStatement(IfStatement.java:282)
        at org.eclipse.jdt.internal.compiler.ast.IfStatement.resolve(IfStatement.java:308)
        at org.eclipse.jdt.internal.compiler.ast.Block.resolve(Block.java:131)
        at org.eclipse.jdt.internal.compiler.ast.IfStatement.resolveIfStatement(IfStatement.java:282)
        at org.eclipse.jdt.internal.compiler.ast.IfStatement.resolve(IfStatement.java:308)
        at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.resolveStatements(AbstractMethodDeclaration.java:661)
        at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.resolveStatements(MethodDeclaration.java:362)
        at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.resolve(AbstractMethodDeclaration.java:570)
        at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1493)
        at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1618)
        at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.resolve(CompilationUnitDeclaration.java:662)
        at org.eclipse.jdt.internal.compiler.Compiler.process(Compiler.java:902)
        at org.eclipse.jdt.internal.compiler.ProcessTaskManager.run(ProcessTaskManager.java:145)
        at java.base/java.lang.Thread.run(Thread.java:832)
```

**Expected behavior**
Eclipse should build the code cleanly without error.

**Version info (please complete the following information):**
 - Lombok version `1.18.18`
 - Platform `Eclipse 4.18.0.I20201202-1800`

**Additional context**
This issue was reported by another user in Eclipse's bug tracker, and closed there: https://bugs.eclipse.org/bugs/show_bug.cgi?id=569908

You can reproduce my eclipse environment exactly by using the following [nix](https://nixos.org) expression:

```
let
  bootstrapPkgs = import <nixpkgs> {};
  
  pinnedPkgs = bootstrapPkgs.pkgs.fetchFromGitHub {
    owner = "jerith666";
    repo = "nixpkgs";
    #commit adding freemarker plugin
    #in future, keep in sync with ../build/developer/rebuild
    rev = "eb8a2a3e95ad408cc9aa0824852f67005293c5dc";
    sha256 = "1015pai7da5dyz522bd4vjwfjr63h5x53pwcln0zh78yzmnwla05";
  };
  nixpkgs = import pinnedPkgs {};
in

with nixpkgs;

with pkgs.eclipses;

let
  lombok = fetchurl {
    url = "https://projectlombok.org/downloads/lombok-1.18.18.jar";
    sha256 = "1k79728943v4c73r3scmqccm82czwx836fsqq31cmyg00ric87k0";
  };

  myEclipse = eclipseWithPlugins {
    eclipse = eclipse-platform;
    jvmArgs = [ "-Xmx2048M"
                "-javaagent:${lombok}" ];
    plugins = with plugins; [
      drools
      freemarker
      jdt
      mat
    ];
  };

in

runCommand "eclipse" {
  buildInputs = [ myEclipse ];
  shellHook = ''
    eclipse;
    exit;
  '';
}
""
```

**Comment by Rawi01** [comment] 2021-03-24 13:41
Seems to be a duplicate of #2752, can you try the [edge version](https://projectlombok.org/download-edge)?

**Comment by jerith666** [comment] 2021-03-24 21:32
Indeed it does.  I only searched by the text of the error, not the method names in the stack trace, so didn't find it, sorry!

I will try to find time to test, but due to work scheduling, I'll likely not get to it until April.

**Comment by jerith666** [comment] 2021-04-15 17:50
I tried 1.18.20, which contains https://github.com/rzwitserloot/lombok/pull/2754/commits/0106746e60263d8cc3fbd189cca7b2e09c3d5c06, and it does fix my issue.  Thanks!

**Closed** 2021-04-15 17:50 UTC
