### ISSUE TITLE
[FEATURE] Could you provide something like "NotNullValidation"?

### ISSUE THREAD

**Issue by JamesChenX** [rzwitserloot/lombok#2244] opened 2019-09-23 00:57 UTC
I need something like "NotNullValidation" that provide a method for a class to check whether all the fields of the class are not null. I think this is very useful for domain objects. Thanks.

Example:
```

@NotNullValidation
@Data
public class Admin {
    private String account;
    private String password;
}
```
```
Admin admin = new Admin();
admin.setAccount("123");
admin.allFieldsNotNull(); // false
```

**Comment by Maaartinus** [comment] 2019-09-23 01:38
I'm afraid, validation in general is out of scope for Lombok. The problem is, there are too many possible options and there are already validation frameworks so powerful that Lombok can never compete with. The `@lombok.NonNull` annotation is not meant to do validation in the usual sense - it helps to find coding errors (rather than user input errors) by failing fast.

**Closed** 2019-10-01 19:06 UTC
