### ISSUE TITLE
Why @NonNull retention is class but not source?

### ISSUE THREAD

**Issue by originalrusyn** [rzwitserloot/lombok#895] opened 2015-08-13 09:23 UTC
I faced with 

java.lang.ClassNotFoundException: lombok.NonNull 

when I started my web app on tomcat that used @NotNull anno with lombok as provided dependency.

**Comment by rspilker** [comment] 2015-08-19 09:14
I do not understand this report. Can you please explain  in a different way what you are doing exactly, what you expected, and what you observe?

Preferably including some code. configuration details, version numbers etc.

**Comment by originalrusyn** [comment] 2015-08-19 09:21
When I tried to run https://github.com/originalrusyn/novotvir/tree/feature/push_job/server war I've faced with :

java.lang.ClassNotFoundException: lombok.NonNull

Can it be because of retention policy of NotNull annotation?

**Comment by rspilker** [comment] 2015-09-22 20:21
No, the problem is that you marked it as `provided`. Lombok is a compile-time only dependency. Recently I've seen a post about someone providing a gradle example. I might be able to find it and add the documentation to the project lombok website.

**Comment by Maaartinus** [comment] 2015-09-23 21:55
> No, the problem is that you marked it as provided. Lombok is a compile-time only dependency. 

AFAIK while plain `compile` means "needed to compile and run`, `providedCompile` means "needed to compile, but when run, someone else will provide it or whatever". So a compile-time only dependency should indeed use `providedCompile`.

A very good reason against `RetentionPolicy.SOURCE` are class file analysis based checkers. The presence of unknown annotations (`RUNTIME`) is specified to be fine, and all the OP gets is a warning. I'd bet that spring is just too curious and precautious.

**Comment by GUIpsp** [comment] 2015-09-23 22:22
> Failed to class-load type while reading annotation metadata. **This is a non-fatal error**, but certain annotation metadata may be unavailable.

**Comment by rzwitserloot** [comment] 2015-10-05 20:08
The general policy on annotations, as applied by javac itself and countless tools, is that an annotation that is not available on the classpath is ignored. One should not whine about this. This goes doubly for class-level retention.

In other words, we consider this a spring bug, being a bit overzealous in reporting this non-fatal error. We will not be addressing this.

**Closed by rzwitserloot** 2015-10-05 20:08 UTC
Labels: parked

**Comment by jvz** [comment] 2016-11-18 16:22
Small followup: this also causes a similar issue in OSGi environments because bnd will add Import-Package directives for lombok because it detects this annotation in the class file. I suppose this is probably a bnd issue if that's the case.
