### ISSUE TITLE
Lombok not working in Java 10

### ISSUE THREAD

**Issue by KrisMuree** [rzwitserloot/lombok#1751] opened 2018-07-01 22:19 UTC
Lombok not working when using java 10. 

Java 10:
Junit 5:
lombok: 1.18.0

![image](https://user-images.githubusercontent.com/12605776/42139416-acfd343e-7dd0-11e8-9f2f-7415997bcb3c.png)

**Comment by arana198** [comment] 2018-07-02 13:23
Lombok does not work with java modules, are you using Java modules? 

I have my project working on Java 10 and Lombok 1.18.0

**Comment by rzwitserloot** [comment] 2018-07-02 20:41
Duplicate of #1723

**Closed by rzwitserloot** 2018-07-02 20:41 UTC
