### ISSUE TITLE
getMethod generate wrong

### ISSUE THREAD

**Issue by cscpswang** [rzwitserloot/lombok#1878] opened 2018-09-29 07:37 UTC
![image](https://user-images.githubusercontent.com/16128945/46242614-84fb3d00-c3fd-11e8-9b30-74981d44e14f.png)
but correct getMethod is getkLevels().

**Comment by janrieke** [comment] 2018-09-29 07:47
Has anyone counted how many duplicates there are for this? :)

I also start thinking that there should be a config option for this...

**Comment by victorwss** [comment] 2018-09-30 16:32
Another duplicate of #504, #757, #1023, #1129, #1030, #1225, #1453, #1454, #1496, #1661 and #1861. Also discussed on https://groups.google.com/d/msg/project-lombok/c9WKYhlfe8k/XQJnL2ABbXYJ and on https://stackoverflow.com/a/49348966/540552.

**Closed** 2018-10-15 19:51 UTC

**Comment by rzwitserloot** [comment] 2021-01-02 14:28
Duplicate of #2693
