### ISSUE TITLE
[BUG]  lose getter/setter method after compile

### ISSUE THREAD

**Issue by wh1zper** [rzwitserloot/lombok#2603] opened 2020-10-10 02:29 UTC
**Describe the bug**
using @Getter or @Setter annotation, when similary but not same word defined as field in Java class, it loses some getter/setter methods after compile

**To Reproduce**

```
@Setter
@Getter
public class Test {

    private JSONObject jCReturnedData;

    private JSONObject jcreturnedData;

    private String mQType;

    private String mqtype;
}
```

![8a8f5ce9-9e2b-4088-9501-fb4ff2b5d93a](https://user-images.githubusercontent.com/52742043/95643632-f4bf5a80-0ae2-11eb-9cfd-1ef278a94de8.png)

after compiled, it loses the getter and setter methods of field of 'jcreturnedData' and 'mqtype'

**Expected behavior**
should retain all the getter/setter methods

**Version info (please complete the following information):**
 - Lombok version 1.18.14
 - Java version 1.8.0_101

**Comment by Rawi01** [comment] 2020-10-10 06:33
This is a duplicate of #2590. The problem is that lombok searches for existing methods without case sensitivity.

**Comment by rzwitserloot** [comment] 2021-01-02 14:11
Duplicate of #2130: We won't fix this, for reasons, see that issue.

**Closed by rzwitserloot** 2021-01-02 14:11 UTC
