### ISSUE TITLE
Feature request: @Cleanup on fields using java.lang.ref.Cleaner

### ISSUE THREAD

**Issue by xnrand** [rzwitserloot/lombok#1647] opened 2018-04-07 13:01 UTC
[`Object.finalize()` is deprecated starting with Java 9](https://docs.oracle.com/javase/9/docs/api/java/lang/Object.html#finalize--). The new [`java.lang.ref.Cleaner`](https://docs.oracle.com/javase/9/docs/api/java/lang/ref/Cleaner.html) is a great way to implement cleanup work that one would traditionally put in a `finalize` method. However, it takes a lot of boilerplate to write a cleaner.

I think it would be great to have `@Cleanup` work on fields where it would generate code utilizing a `Cleaner`. As a fallback for compiling code for older java versions, it could generate a `finalize` method.

However, this may prove tricky to do for non-final fields because a Cleaner may not hold a reference to the object it is affiliated with:

<blockquote cite="https://docs.oracle.com/javase/9/docs/api/java/lang/ref/Cleaner.html">
Note that the cleaning action must not refer to the object being registered. If so, the object will not become phantom reachable and the cleaning action will not be invoked automatically.<br>
&mdash; https://docs.oracle.com/javase/9/docs/api/java/lang/ref/Cleaner.html
</blockquote>

**Comment by xnrand** [comment] 2018-04-07 14:44
@Maaartinus Right now I'm working with an API (wrapped native library) that expects one to call close() to clean up native resources. While it _shouldn't_ happen that a close() is forgotten, I'm using `Cleaner`s to ensure that anything that might have been leaked gets cleaned up when its corresponding object gets collected.

**Comment by Maaartinus** [comment] 2018-04-07 15:24
@xnrand OK, so you have to write many `Cleaner`s, right? The problem is that there are so many feature coming in and that implementing (and maintaining!) anything with Lombok is way harder than using standard annotation processing (as the latter is fully supported, while Lombok works in gray areas). So only the most wanted features get a chance (I'm not a project author, but that's what one of them wrote).

I wonder if the cleaners can be generated using annotation processing or reflection?

**Comment by randakar** [comment] 2018-04-08 07:13
The official way to ensure close is called on opened resources is the
try-with resources statement.
https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html

If you don't have control over the call sites you have a different problem
though.

Op za 7 apr. 2018 17:24 schreef Maaartinus <notifications@github.com>:

**Comment by rspilker** [comment] 2018-04-09 22:32
You suggest `@Cleanup` on a field. I assume that would mean that if a value is assigned to the field and this object is eligible for garbage collection, we ensure the field is explicitly "closed", whatever that might mean. 

There are some pretty big gotchas here:
- Where would we get the cleaner instance from. We shouldn't create one for each class, since that spawns a whole thread.
- The cleanup code executed must be in a static context (not referencing the outer object). But we need the value of the field. Lombok can obviously generate code. In this case, we would need to generate a class, containing the reference to the resource and the cleanup code in the `run` method. 
- We would need to create a field containing an instance of that class, and a (private) getter to give the containing class access to the resource. We probably should re-use the original field, and change the type.

Although I do see the opportunity to reduce a lot of boiler-plate, I don't think this is used common enough to warrant our time.

**Closed by rspilker** 2018-04-09 22:32 UTC
