### ISSUE TITLE
[bug][v1.18.2] when use @Builder(toBuilder = true) and @Singular with null list

### ISSUE THREAD

**Issue by ccone1995** [rzwitserloot/lombok#1834] opened 2018-08-27 05:37 UTC
java source:
```
@Builder(toBuilder = true)
public final class LombokBug {
    @Singular
    private List<OrderBy> nullables;
}
```
class source:
```
public LombokBug.LombokBugBuilder toBuilder() {
    return (new LombokBug.LombokBugBuilder()).nullables(this.nullables);
}
public LombokBug.LombokBugBuilder nullables(Collection<? extends OrderBy> nullables) {
    if(this.nullables == null) {
        this.nullables = new ArrayList();
    }
    this.nullables.addAll(nullables);
    return this;
}
```
exception:
```
java.lang.NullPointerException: null
        at java.util.ArrayList.addAll(ArrayList.java:581)
```

**Comment by rzwitserloot** [comment] 2018-08-27 21:03
This is a duplicate of #1812.

We've fixed this in the edge release :) - https://projectlombok.org/download-edge

**Closed by rzwitserloot** 2018-08-27 21:03 UTC
