### ISSUE TITLE
[BUG] The default setter may expose internal representation

### ISSUE THREAD

**Issue by afmenez** [rzwitserloot/lombok#2152] opened 2019-06-07 19:23 UTC
**Describe the bug**
The default setter may expose internal representation by incorporating a reference to a mutable object.

**To Reproduce**
```
public class Account {
    @Setter
    private Date creation;
}
```
**Expected behavior**
I expect the setter to clone the external object:
```
	public void setCreation(Date creation) {
		this.creation = (Date) creation.clone();
	}
```
**Version info (please complete the following information):**
 - Lombok version 1.18.8
 - Platform (Eclipse, Java JDK 11)

**Additional context**
I found this issue with the SpotBugs static analyzer for Eclipse.

**Comment by Maaartinus** [comment] 2019-06-07 21:30
Exact duplicate of #2151.

**Comment by afmenez** [comment] 2019-06-08 00:04
That is about the setter, this one about the getter.  They are very similar, indeed.

**Comment by rspilker** [comment] 2019-06-17 18:36
Yeah, not a lot we can do without a lot more work. Regarding `Date`s, the better alternative is to use the more modern immutable representations, like `LocalDate`.

**Closed by rspilker** 2019-06-17 18:36 UTC
