### ISSUE TITLE
ExtensionMethod  failed to compile in Eclipse

### ISSUE THREAD

**Issue by daniel-exceed** [rzwitserloot/lombok#1695] opened 2018-05-16 07:50 UTC
using lombok 18 in exlipse oxygen 4.7.3.a, im trying to use this extensions class:
public class ReflectionUtils {
	public static String getAnnotationValue(Class<?> clazz, Class<? extends Annotation> anno) {
		if (!clazz.isAnnotationPresent(anno)) {
			return null;
		}
		
		try {
			return (String)anno.getDeclaredMethod("value").invoke(clazz.getAnnotation(anno));
		} catch (IllegalArgumentException | IllegalAccessException | SecurityException | InvocationTargetException | NoSuchMethodException e) {
			return null;
		}
	}
}

in another class like this:
@ExtensionMethod({ReflectionUtils.class})

and call it like this:
public String getField(Class<?> clazz, String field) {
		return FieldsMap.get(**_clazz.getAnnotationValue(Entity.class)_**).get(field);
	}

my eclipse cant compile the entire class claiming:
Internal compiler error: java.lang.ArrayIndexOutOfBoundsException
maven compiles fine.
also, when i use an extension method with only 1 parameter (the object i extend) it compiles fine.

what can be done to make it work?

im attatching the error log of eclipse

[lombok error.log](https://github.com/rzwitserloot/lombok/files/2008026/lombok.error.log)

**Comment by johnthuss** [comment] 2019-11-26 17:03
I have the same/simliar problem in Eclipse. It does compile successfully using javac however.

```import java.util.Map;
import java.util.Optional;
import lombok.experimental.ExtensionMethod;

class Extensions {
	public static <K, V> Optional<V> getOpt(Map<K, V> map, K key) {
		return Optional.ofNullable(map.get(key));
	}
}
@ExtensionMethod({Extensions.class})
public class Main2 {
	public static void main(String[] args) {
		Map<String, Integer> map = Map.of("key", 1);
		System.out.println(map.getOpt("missing"));
	}
}
```

Errors occurred during the build.
Errors running builder 'Java Builder' on project 'MyProject'.
java.lang.ArrayIndexOutOfBoundsException

**Comment by Maaartinus** [comment] 2019-11-26 20:27
The same for me, using Lombok 1.18.6. and Eclipse
Version: 2018-09 (4.9.0)
Build id: 20180917-1800

I could simplify the code to
```
public class Extensions {
	public static Optional<String> getOpt(String s, int index) {
		return Optional.ofNullable(null);
	}
}

@ExtensionMethod({Extensions.class})
public class Main2 {
	public static void main(String[] args) {
		final String s = "a";
		System.out.println(s.getOpt(7));
	}
}
```
The problem disappears when I remove the `index` argument.

**Comment by rzwitserloot** [comment] 2020-02-27 21:44
Duplicate of #1441

**Closed by rzwitserloot** 2020-02-27 21:44 UTC
