### ISSUE TITLE
[ BUILD FAILED] build version 1.18.12, failed

### ISSUE THREAD

**Issue by rolandhe** [rzwitserloot/lombok#2511] opened 2020-07-08 13:07 UTC
I clone tag 1.18.12, and run "ant dist" to build, met exception:

compile errors: 
----------
1. ERROR in ~/work/lombok/lombok-1.18.12/src/core/lombok/eclipse/handlers/EclipseHandlerUtil.java (at line 2436)
			if (mth.returnType.annotations == null) mth.returnType.annotations = new Annotation[len][];
			                   ^^^^^^^^^^^
annotations cannot be resolved or is not a field

**Comment by Rawi01** [comment] 2020-07-08 16:54
This is a duplicate of #2363.
If you want to compile exactly that version you can apply the fix (0401f49fa6975195f81ff3252fefdbd6409dde6b) yourself or checkout the current master branch. After that run `ant distclean` to cleanup the old stuff.

**Closed** 2021-02-07 16:13 UTC
