### ISSUE TITLE
Bug report: auto generate setter method name error when the property is starts with a character

### ISSUE THREAD

**Issue by shijiebei2009** [rzwitserloot/lombok#1453] opened 2017-08-10 02:50 UTC
when I have a property uName in a javabean, according to the javabean specification for setter/getter method name, it should be setuName and getuName, but the lombok auto generate method name is setUName and getUName.

lombok version in IDEA
<dependency>
  <groupId>org.projectlombok</groupId>
  <artifactId>lombok</artifactId>
  <version>1.16.12</version>
</dependency>

**Comment by Maaartinus** [comment] 2017-08-10 07:09
I'm not a project owner, but I'd bet, it won't get changed:
https://github.com/rzwitserloot/lombok/issues/757#issuecomment-121403588
The problem is that the javabeans crapification base classes are themselves inconsistent (`NameGenerator` vs `Introspector`). Given it has simple and logical rules like "every second Friday, when the field name contains two vowels, use the `¯\_(ツ)_/¯` prefix" (btw. that is a valid Java identifier), I can't say I'm surprised.

Duplicate of #757

**Closed** 2018-04-23 20:00 UTC

**Comment by rzwitserloot** [comment] 2021-01-02 14:30
Duplicate of #2693
