### ISSUE TITLE
Annotations on constructor parameters for @RequiredArgsConstructor and @AllArgsConstructor

### ISSUE THREAD

**Issue by victorwss** [rzwitserloot/lombok#1663] opened 2018-04-17 21:33 UTC
I'm aware that you can add annotations to the constructors generated by `@RequiredArgsConstructor`, `@AllArgsConstructor` and `@NoArgsConstructor` by using the `onConstructor_ = {annotation, otherAnnotation}`.

However, what about the parameters of the constructors in `@RequiredArgsConstructor`, `@AllArgsConstructor`? How can I specify them without having to hand-write the constructor?

I digged through the documentation and through the `HandleConstructor.java` file and did not found anything other than `@NonNull` and `@Nullable`. So, I propose something like that:

```java
@AllArgsConstructor(onConstructor_ = @JsonCreator)
public class Foo {
    @ConstructorParam(@JsonProperty("bar"))
    @NonNull
    private String bar;

    @ConstructorParam(@JsonProperty("jog"))
    private @NonNull SomeOtherThing jog;
}
```

The annotation `@ConstructorParam` would be handled by the same handler that handles `@RequiredArgsConstructor` and `@AllArgsConstructor`.

By the way, this could be raised one step further with an hypothetical `@EveryField` annotation:

```java
@AllArgsConstructor(onConstructor_ = @JsonCreator)
@EveryField(onField_ = {
    @NonNull,
    @ConstructorParam(@JsonProperty("{lombok-field-name}"))
})
public class Foo {
    private String bar;
    private SomeOtherThing jog;
}
```

**Comment by Maaartinus** [comment] 2018-04-17 21:49
Duplicate of #1335. Instead of `@EveryField`, I [proposed](https://github.com/rzwitserloot/lombok/issues/1335#issuecomment-289249534) a configuration.

**Comment by rspilker** [comment] 2018-04-23 21:51
use case added here:

https://github.com/rzwitserloot/lombok/wiki/FEATURE-IDEA:-Annotation-based-Include-Exclude-for-ToString,-EqualsAHC,-etc

**Closed by rspilker** 2018-04-23 21:51 UTC
