### ISSUE TITLE
Wrong getter/setter names for generated for certain corner cases

### ISSUE THREAD

**Issue by janzyka** [rzwitserloot/lombok#1129] opened 2016-06-13 07:43 UTC
Lombok generates non-valid getter names for certain corner cases of Java Bean specification.

Namely fields which have second letter uppercase like `xAxis` or `iMessage` should become `setxAxis(...)` and `setiMessage(...)` - not very intuitive but it seems to be that way. Lombok on the other hand generates `setXAxis(...)` and `setIMessage(...)`.

This issue usually doesn't do much harm until you do something like deserialize object annotated via `@Data` through Jackson. In this case those fields remain unset because no setter _with valid name_ exists for such fields.

There is a [blog post](http://dertompson.com/2013/04/29/java-bean-getterssetters/) explaining this issue nicely.

**Comment by nickle-ye** [comment] 2016-08-08 03:03
Yes, I met the same issue when using fasterxml.jackson to generate xml from javabean, which has used the "@Data"

And you can find the related doc from oracle about this:
http://download.oracle.com/otndocs/jcp/7224-javabeans-1.01-fr-spec-oth-JSpec/

Please refer to below section:
8.3.1 Simple properties
8.3.2 Boolean properties
8.8 Capitalization of inferred names.

> Thus when we extract a property or event name from the middle of an existing Java name, we
> normally convert the first character to lower case. However to support the occasional use of all
> upper-case names, we check if the first two characters of the name are both upper case and if
> so leave it alone. So for example,
> “FooBah” becomes “fooBah”
> “Z” becomes “z”
> “URL” becomes “URL”
> We provide a method Introspector.decapitalize which implements this conversion rule.

I think it would be better to fix this bug asap, otherwise, some magic bug would be hard to found.

**Comment by askoning** [comment] 2017-02-22 12:00
See #504 , #757 for older discussions on this.

**Comment by anddero** [comment] 2020-09-01 05:32
In #757 this was dropped due to Java community being split on the topic. I still believe it *is* worth the hassle and could be fixed in the next major release. Or include a new `strict` parameter for the `@Getter`, `@Setter` and `@Data` annotations to allow including this functionality without any breaking changes.

**Comment by randakar** [comment] 2020-09-01 05:59
There is a simpler workaround for Jackson: The new '@Jacksonize' annotation that is in the edge release, possibly with '@JsonProperty' / '@JsonGetter' on any fields still having issues.

As for the whole bean naming issue: The whole point of it is that there is no single spec everyone adheres to. There *is no such thing* as 'strict' when doing that breaks half of the world.

**Comment by Rawi01** [comment] 2020-09-01 06:46
@anddero You can also add `@Setter(AccessLevel.NONE) @Getter(AccessLevel.NONE)` to the field you want to exclude, that might be easier if there are only one or two fields.

One of the maintainers already [mentioned](https://github.com/rzwitserloot/lombok/issues/1861#issuecomment-429989684) that they will accept a PR that changes this (unfortunately only without a config key to get back the current behaviour...).

**Comment by anddero** [comment] 2020-09-01 07:04
It seems, when you have a custom accessor like `getxAxis()`, Lombok detects this and **does not** generate an additional `getXAxis()`. This makes the workarounds much simpler.

**Comment by rzwitserloot** [comment] 2021-01-02 14:30
Duplicate of #2693

**Closed by rzwitserloot** 2021-01-02 14:30 UTC
