### ISSUE TITLE
@Data注解时生成的getter,setter方法在有些属性会有问题！！！

### ISSUE THREAD

**Issue by initcap** [rzwitserloot/lombok#1861] opened 2018-09-13 11:49 UTC
eg:private String cMc;

@Data时：public String getCMc(){}; 
但是idea自动生成的是public String getcMc(){};

造成的实质性后果：
SpringMVC处理@Data注解时，返回给前端时cmc
SpringMVC处理idea生成的时，返回给前端的是cMc

导致前端拿这个返回字段给后端时，后端不能接收cmc的值。

**Comment by victorwss** [comment] 2018-09-13 14:53
Translating that into English with the help of Google translator, it seems to be that:

> Eg:
>
> ```java
> private String cMc;
> 
> @Data: public String getCMc(){};
> ```
>
> But idea automatically generates a `public String getcMc(){};`
>
> Substantial consequences:
>
> When SpringMVC processes the `@Data` annotation, it returns to the frontend when `cmc`
> When SpringMVC processes the idea generation, it is `cMc` that is returned to the front end.
>
> When the front end takes this return field to the backend, the backend cannot receive the value of `cmc`.

Seems to be another duplicate of #757, #1453, #1454, #1496 and #1661 and possibly others.

**Comment by qingqingmanong** [comment] 2018-09-14 07:00
public static void main(String[] args) {
		String prefix = "get";
		String suffix = "oFo";
		log.info("【源码结果】:{}",buildAccessorName(prefix,suffix));
		log.info("【改正结果】:{}",buildAccessorNameModified(prefix,suffix));
	}

	/**
	 * 【lombok源码问题片段】
	 * 位置:git@github.com:rzwitserloot/lombok.git/src/core/lombok/core/handlers/Handler.java 434行
	 */
	public static String buildAccessorName(String prefix, String suffix) {
		if (suffix.length() == 0) return prefix;
		if (prefix.length() == 0) return suffix;

		char first = suffix.charAt(0);
		if (Character.isLowerCase(first)) {
			boolean useUpperCase = suffix.length() > 2 &&
					(Character.isTitleCase(suffix.charAt(1)) || Character.isUpperCase(suffix.charAt(1)));
			suffix = String.format("%s%s",
					useUpperCase ? Character.toUpperCase(first) : Character.toTitleCase(first),
					suffix.subSequence(1, suffix.length()));
		}
		return String.format("%s%s", prefix, suffix);
	}

	public static String buildAccessorNameModified(String prefix, String suffix) {
		if (suffix.length() == 0) return prefix;
		if (prefix.length() == 0) return suffix;

		char first = suffix.charAt(0);
		if (Character.isLowerCase(first)) {
			boolean useUpperCase = suffix.length() > 2 &&
					(Character.isTitleCase(suffix.charAt(1)) || Character.isUpperCase(suffix.charAt(1)));
			suffix = String.format("%s%s",
					useUpperCase ? first : Character.toTitleCase(first),
					suffix.subSequence(1, suffix.length()));
		}
		return String.format("%s%s", prefix, suffix);
	}

**Comment by victorwss** [comment] 2018-09-14 17:32
Ok, lets translate that:
源码结果 -> Source code results
改正结果 -> Correct result (or perhaps, expected result)
lombok源码问题片段 -> Lombok source code fragment
位置 -> at
434行 -> Line 434

Well, there is no class `Handler`. Maybe you are referring to this: https://github.com/rzwitserloot/lombok/blob/ad21a1573bab57c63ffd5b9867f8e19ac7f0c94b/src/core/lombok/core/handlers/HandlerUtil.java#L434-L447

I see that your suggestion is to use just `first` in the place of `Character.toUpperCase(first)`. But this have some problems about retrocompatibility and that the Java Beans spec is basically broken in this corner case.

Further duplicates: #504, #1023, #1129, #1225, #1030.

So, please:
* Read the text of the duplicates.
* Read this discussion: https://groups.google.com/d/msg/project-lombok/c9WKYhlfe8k/XQJnL2ABbXYJ
* Don't post text in Chinese here because very few people in this community would be able to understand it. If you can't write in English, use google translator (or whatever tool you have) just as I did even if the result is not very precise.

**Comment by victorwss** [comment] 2018-09-14 17:35
Oh, very relevant to this: https://stackoverflow.com/a/49348966/540552

**Comment by qingqingmanong** [comment] 2018-09-15 02:55
Ok, thank you, you are correct, I have learned a lot, thank you very much!

**Comment by rspilker** [comment] 2018-10-15 19:51
@Maaartinus No, but we would accept a pull request that does change the behavior and breaks backwards compatibility. Counting the number of issues, we made a mistake. 

We would most likely use the 2.x release to introduce this change. 

We do not want to introduce config keys because that clutters up the code, resulting in more code to maintain than if we make a clean break.

For us, the best pull request is already squashed to a single changeset, and includes also the modified test code.

Please keep in mind that this might also affect other code like `@Builder` and `@Wither`.

**Comment by TGhoul** [comment] 2018-11-18 11:42
@qingqingmanong 你好，请问你的问题解决了吗？

**Comment by ChunMengLu** [comment] 2019-01-30 02:18
Same problem！

**Comment by lvchangqi** [comment] 2019-04-24 07:21
the best way to resolve it using "overload"

**Comment by gtskaushik** [comment] 2019-09-23 07:42
I am facing the same issue. I understand the compatibility issue. But recommend to re-consider since this has affected a lot many users

**Comment by pigxcloud** [comment] 2019-12-05 04:45
Same problem！

**Comment by xhwutao** [comment] 2019-12-05 05:27
Same problem！

**Comment by D-T-Y** [comment] 2019-12-05 07:21
Same problem！

**Comment by janrieke** [comment] 2019-12-05 10:29
Then do something instead of posting those +1's. The maintainers already stated over a year ago that they'd accept a PR that changes this.

**Comment by gongdelang** [comment] 2020-07-16 03:27
Same problem！

**Comment by AndyZhangdsa** [comment] 2020-08-20 08:49
Same problem！

**Comment by li-xunhuan** [comment] 2020-10-20 07:13
Same problem！

**Comment by rzwitserloot** [comment] 2021-01-02 14:28
Duplicate of #2693

**Closed by rzwitserloot** 2021-01-02 14:28 UTC
